LightDotSo/LightDotSo

.gitmodules
- forge install: safe-contracts
- chore: ini safe
=> chore: ini safe

.gitmodules, remappings.txt
=> chore: update libs

.github/workflows/k8s.yml
- chore: ini k8s serve
- chore: update credentials gke
=> chore: ini update gke credentials

.changeset/chilly-humans-sort.md, .changeset/four-coats-guess.md, .changeset/large-ears-tap.md, Cargo.toml, Makefile, android/package.json, android/turbo.json, contracts/package.json, crates/core/misc/apple/Info.plist, ios/LightWallet.xcodeproj/project.pbxproj, ios/LightWallet.xcodeproj/xcshareddata/xcschemes/LightWallet.xcscheme, ios/LightWallet.xcodeproj/xcshareddata/xcschemes/LightWalletDev.xcscheme, ios/LightWallet.xcodeproj/xcshareddata/xcschemes/LightWalletTests.xcscheme, ios/LightWallet.xcodeproj/xcshareddata/xcschemes/LightWalletUITests.xcscheme, ios/turbo.json, rust-toolchain.toml
- chore: refactor makefile
- Update Cargo.toml
=> chore: ini update v2

.github/workflows/contracts.yml, contracts/size.sh, contracts/turbo.json
=> chore: update contracts flow v2

.github/dependabot.yml, .taplo.toml
=> chore: refactor dependabot

.github/workflows/neon.yml
- chore: ini preview
- chore: ini final
=> chore: ini final

apps/api/.env.development, apps/app/.env.development, apps/app/app/page.tsx, configurations/kysely/index.ts, configurations/kysely/package.json, configurations/kysely/turbo.json, packages/auth/index.ts, pnpm-lock.yaml
- feat: ini auth prisma
- feat: ini prisma page
=> feat: ini auth prisma

Cargo.lock, bin/Cargo.toml, bin/src/bin/indexer.rs, configurations/prisma/prisma/migrations/20230805190748_add_testnet_config/migration.sql, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/db/src/db.rs, crates/indexer/src/config.rs, crates/indexer/src/constants.rs, crates/indexer/src/indexer.rs
- feat: ini indexer bin
- feat: ini testnet config
- feat: ini testnet flag
=> feat: ini indexer bin

apps/app/app/layout.tsx, apps/open/public/index.html
- chore: ini debug
- chore: ini open layout
=> chore: ini open

Cargo.lock, Cargo.toml, crates/indexer/Cargo.toml, crates/indexer/src/indexer.rs
- perf: ini autometrics
- perf: ini retries
- perf: ini retries
- perf: ini retries
=> feat: ini retries

Cargo.lock, rust-toolchain.toml
- perf: fix week 7
- chore: ini cargo nightly
=> chore: update cargo

Cargo.lock, Cargo.toml, Dockerfile, bin/Cargo.toml, bin/src/bin/prometheus.rs
- perf: ini reverse proxy
- perf: ini fly token
=> perf: ini reverse proxy

fly/otel-collector/otel_config.yml
An attempted fix for the otel collector on fly, given the error log here: https://github.com/LightDotSo/LightDotSo/actions/runs/5907616750/job/16026350383
=> Possible fix for otel collector prometheus remote write endpoint url

.github/workflows/rust.yml, crates/consumer/src/consumer.rs
=> chore: fix rust gha

Cargo.lock, Cargo.toml, bin/src/bin/consumer.rs, crates/consumer/Cargo.toml, crates/consumer/src/config.rs, crates/consumer/src/consumer.rs, crates/db/Cargo.toml, crates/db/src/db.rs, crates/indexer/Cargo.toml, crates/indexer/src/indexer.rs, crates/redis/Cargo.toml, crates/redis/src/lib.rs, crates/redis/src/namespace.rs, crates/tracing/Cargo.toml, crates/tracing/src/lib.rs, crates/tracing/tests/lib.rs
- refactor: tracing crates
- perf: add instument futures
=> perf: refactor light tracing

crates/consumer/src/consumer.rs, crates/indexer/src/config.rs, crates/indexer/src/indexer.rs
=> feat: ini indexer config

crates/bundler/src/opts.rs, crates/rpc/src/lib.rs, thunder-tests/thunderActivity.json
=> fix: ini ip v6

Cargo.lock, Cargo.toml, bin/Cargo.toml, bin/src/bin/paymaster.rs, bin/src/bin/rpc.rs, crates/axum/Cargo.toml, crates/axum/src/lib.rs, fly/gas/fly.toml, fly/paymaster/fly.toml, fly/simulator/fly.toml, thunder-tests/thunderActivity.json
=> feat: ini internal rpc

bin/src/bin/rpc.rs, crates/rpc/src/config.rs, crates/rpc/src/constants.rs, crates/rpc/src/lib.rs, thunder-tests/thunderActivity.json
=> chore: refactor rpc

bin/src/bin/consumer.rs
=> chore: revert multi

bin/src/bin/consumer.rs
=> feat: ini multi threads

crates/indexer/src/constants.rs, crates/indexer/src/indexer.rs, fly/consumer/fly.toml, thunder-tests/thunderActivity.json
- perf: remove mainnet and gnosis from runner
- fix: remove assert_eq
=> chore: ini failsafe

bin/src/bin/consumer.rs, fly/consumer-tx/fly.toml
=> fix: error safe revert

.github/workflows/contracts.yml, crates/rpc/src/lib.rs
=> chore: update rpc

crates/rpc/src/constants.rs
=> chore: ini eth sepolia

crates/rpc/src/constants.rs, crates/rpc/src/lib.rs
- perf: ini eth sepolia rpc
- chore: ini eth public
=> chore: ini eth public

crates/tracing/src/lib.rs, fly/loki/fly.toml, fly/tempo/fly.toml, fly/tempo/tempo-config.yaml
https://fly.io/blog/rust-memory-leak/
https://github.com/open-telemetry/opentelemetry-rust/issues/956
=> fix: memory leak

crates/tracing/src/lib.rs, fly/grafana-agent/fly.toml, fly/loki/Dockerfile, fly/loki/fly.toml, fly/loki/loki-config.yaml, fly/tempo/Dockerfile, fly/tempo/fly.toml, fly/tempo/tempo-config.yaml
=> fix: memory

fly/loki/fly.toml, fly/loki/loki-config.yaml, fly/tempo/Dockerfile, fly/tempo/fly.toml, fly/tempo/tempo-config.yaml
- fix: loki run
- chore: update tempo
=> fix: loki run

crates/axum/src/api.rs, crates/axum/src/routes/check.rs, crates/axum/src/routes/health.rs, crates/axum/src/routes/wallet.rs
- fix: ini query optional
- fix: ini v1
=> fix: ini v1

.github/workflows/deploy.yml, .github/workflows/graphql.yml, .license-check-and-add-config.json, .prettierignore, Cargo.lock, Cargo.toml, apps/subgraph/package.json, crates/graphql/Cargo.toml, crates/graphql/build.rs, crates/graphql/schemas/graph.graphql, crates/graphql/src/lib.rs, crates/graphql/src/snapshots/lightdotso_graphql__test__running_query.snap, crates/graphql/src/snapshots/lightdotso_graphql__test__snapshot_test_query.snap
- fix: ini base testnet
- feat: ini graphql
- chore: ini graphql gha
=> feat: ini graphql

.github/workflows/graphql.yml, contracts/script/base/BaseLightDeployer.s.sol, contracts/script/base/BaseLightDeployerFlow.s.sol, foundry.toml, thunder-tests/collections/tc_col_rpclightso.json
- chore: v2
- chore: v2
- chore: v2
=> chore: ini sig

crates/bundler/src/config.rs, crates/bundler/src/eth.rs, crates/bundler/src/eth_api.rs, crates/paymaster/src/config.rs
=> feat: ini send

contracts/script/base/BaseLightDeployer.s.sol, contracts/script/base/BaseLightDeployerFlow.s.sol, crates/paymaster/src/paymaster.rs, crates/paymaster/src/paymaster_api.rs, crates/rpc/src/lib.rs, thunder-tests/collections/tc_col_local.json
- fix: successful deployer sig
- perf: ini paymaster stash
=> perf: ini chainid

contracts/script/base/BaseLightDeployer.s.sol, contracts/script/flow/LightVerifyingPaymasterVerifyFlow.s.sol, crates/paymaster/src/paymaster.rs, crates/paymaster/src/types.rs, foundry.toml
=> fix: debug pm

contracts/script/base/BaseLightDeployer.s.sol, contracts/script/base/BaseLightDeployerFlow.s.sol, contracts/script/flow/LightVerifyingPaymasterVerifyFlow.s.sol, contracts/test/base/BaseTest.t.sol, contracts/test/fork/entrypoint/simulation/EntrypointSimulateValidation.f.sol, crates/gas/src/chains/ethereum.rs, crates/gas/src/chains/mod.rs, crates/gas/src/chains/polygon.rs, crates/gas/src/gas.rs, crates/paymaster/src/paymaster.rs, thunder-tests/collections/tc_col_rpclightso.json
=> feat: ini brady

.github/workflows/fly.yml, .vscode/settings.json, Cargo.lock, Cargo.toml, bin/src/bin/polling.rs, crates/axum/Cargo.toml, crates/axum/src/api.rs, crates/axum/src/result.rs, crates/axum/src/routes/configuration.rs, crates/axum/src/routes/mod.rs, crates/axum/src/routes/wallet.rs, crates/consumer/src/consumer.rs, crates/contracts/src/constants.rs, crates/db/src/db.rs, crates/graphql/src/polling/light_wallets.rs, crates/graphql/src/polling/min_block.rs, crates/graphql/src/polling/mod.rs, crates/graphql/src/polling/snapshots/lightdotso_graphql__polling__light_wallets__test__snapshot_test_query.snap, crates/graphql/src/polling/snapshots/lightdotso_graphql__polling__min_block__test__snapshot_test_query.snap, crates/opentelemetry/src/lib.rs, crates/opentelemetry/src/polling.rs, crates/polling/Cargo.toml, crates/polling/src/config.rs, crates/polling/src/polling.rs, crates/solutions/Cargo.toml, crates/solutions/src/lib.rs, fly/polling-live/fly.toml, fly/polling-past/fly.toml
- feat: ini db client
- chore: update opentelemetry metrics
- feat: working wallet
- perf: update min blcok
=> feat: ini db

configurations/prisma/prisma/migrations/20231004010310_optional_configuration_id/migration.sql, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/routes/wallet.rs
=> feat: ini revamp db

crates/solutions/src/builder.rs, crates/solutions/src/config.rs, crates/solutions/src/lib.rs, crates/solutions/src/node.rs, crates/solutions/src/snapshots/lightdotso_solutions__builder__tests__config_1.snap, crates/solutions/src/snapshots/lightdotso_solutions__builder__tests__config_2.snap, crates/solutions/src/snapshots/lightdotso_solutions__builder__tests__config_3.snap, crates/solutions/tests/it/config.rs
=> feat: ini builder

Cargo.lock, Cargo.toml, crates/package.json
=> fix: cargo impl

apps/app/app/(authenticated)/new/configuration/configuration-form.tsx, apps/app/app/(authenticated)/new/confirm/confirm-form.tsx, apps/app/app/(authenticated)/new/confirm/page.tsx, apps/app/src/schemas/newForm.ts, apps/app/src/stores/useNewForm.ts
- feat: ini config
- perf: update
- perf: ini confirm type
- perf: update
=> feat: ini type

apps/app/src/components/wallet-switcher.tsx, crates/db/src/db.rs, packages/client/src/index.ts, packages/client/src/v1.d.ts
=> feat: ini wallet ls

apps/app/app/(wallet)/[address]/@transaction/(.)transaction/[chainId]/page.tsx, apps/app/app/(wallet)/[address]/settings/page.tsx, apps/app/src/components/transaction-dialog.tsx, apps/app/src/handles/[address].ts, crates/axum/src/api.rs, crates/axum/src/routes/configuration.rs, packages/client/src/v1.d.ts
- feat: ini owner id
- feat: ini configuration owner
=> feat: ini configuration owner

apps/app/src/components/transaction-dialog.tsx, apps/ui/src/providers/web3.tsx, crates/axum/src/routes/user_operation.rs, crates/indexer/src/indexer.rs, crates/solutions/src/signature.rs, crates/solutions/src/utils.rs, package.json, patches/@wagmi__core@1.4.4.patch, pnpm-lock.yaml
- fix: hash msg
- feat: ini sig
=> fix: hash msg

apps/subgraph/package.json, apps/subgraph/src/light-wallet.ts
=> fix: light wallet

apps/app/src/components/transaction-dialog.tsx, crates/axum/src/api.rs, crates/axum/src/routes/user_operation.rs, packages/client/package.json, packages/client/src/index.ts, packages/client/src/v1.d.ts
=> feat: refactor create user operation

crates/gas/src/chains/ethereum.rs, crates/gas/src/chains/polygon.rs, crates/gas/src/config.rs, crates/gas/src/gas.rs, crates/gas/src/gas_api.rs, crates/gas/src/lib.rs, crates/gas/src/server.rs, crates/paymaster/src/config.rs, crates/paymaster/src/lib.rs, crates/paymaster/src/paymaster.rs, crates/paymaster/src/server.rs, thunder-tests/collections/tc_col_local.json
- feat: ini server impl paymaster
- fix: rpc server
=> fix: rpc server

apps/app/app/(authenticated)/error.tsx, apps/app/app/(authenticated)/wallets/page.tsx, apps/app/app/(unauthenticated)/error.tsx, apps/app/app/(wallet)/[address]/error.tsx, apps/app/app/global-error.tsx, apps/app/app/root.tsx, apps/app/src/components/auth-state.tsx, apps/app/src/components/feedback-form.tsx, apps/app/src/components/feedback-popover.tsx, apps/app/src/components/sidebar-nav.tsx, apps/app/src/components/wallet-switcher.tsx, apps/app/src/stores/useAuth.ts, fly/polling-live/fly.toml, fly/polling-past/fly.toml, fly/polling/fly.toml
- chore: refactor polling ls
- chore: update sidebar nav
- fix: wallet switcher
- feat: ini feedback form
=> chore: refactor polling ls

Cargo.lock, apps/app/app/(wallet)/[address]/transactions/all/page.tsx, apps/app/src/services/getCachedUserOperations.ts, contracts/script/LightVerifyingPaymasterDeployer.s.sol, contracts/test/base/BaseTest.t.sol, crates/paymaster/Cargo.toml, crates/paymaster/src/constants.rs, crates/paymaster/src/paymaster.rs, crates/paymaster/tests/it/main.rs
- feat: ini v3
- chore: ini hash bytes
=> feat: ini v3 deployer

crates/graphql/src/traits.rs, crates/polling/src/polling.rs
=> fix: parsing traits

configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/db/src/db.rs, crates/graphql/src/traits.rs, crates/indexer/src/indexer.rs, crates/polling/src/polling.rs
- fix: traits create
- feat: ini trcing
=> fix: crate

crates/db/src/db.rs
- perf: update
- chore: link uo to tx
=> fix: db attr

configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/api.rs, crates/axum/src/routes/user_operation.rs, crates/db/src/db.rs, packages/client/src/v1.d.ts
- perf: update
- feat: ini user operation api tx
- chore: ini uo nonce
=> feat: ini uo api

crates/db/src/db.rs
- perf: update
- fix: crate db
=> fix: crate db

apps/app/src/components/main-nav.tsx, apps/app/src/hooks/useTabs.ts, crates/axum/src/routes/wallet.rs, packages/client/src/index.ts, packages/client/src/v1.d.ts
- feat: ini wallet tab
- feat: ini wallet tab
- perf: ini tab id
=> fix: ini wallet tab

configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/routes/wallet.rs
- feat: ini prisma user address require
=> feat: ini prisma

crates/axum/src/routes/user_operation.rs, crates/solutions/src/config.rs, crates/solutions/src/node.rs, crates/solutions/src/recover.rs, crates/solutions/src/signature.rs, crates/solutions/tests/it/signatures.rs, crates/solutions/tests/samples/wallet_reduced_config_after.json, crates/solutions/tests/samples/wallet_reduced_config_before.json, thunder-tests/collections/tc_col_local.json
- feat: refactor solutions
- perf: ini reduced after
- perf: ini signer nodes
=> feat: ini refactor solutions

apps/app/src/inngest/walletPortfolioSet.ts, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, packages/const/src/ChainIds.ts, packages/schemas/test/llama.spec.ts, packages/schemas/test/mocks/llama.json, packages/schemas/tsconfig.json, vitest.workspace.ts
- feat: refactor prisma wallet balance refactor
- feat: ini erc20 id
=> feat: ini prisma 

apps/app/app/(wallet)/[address]/page.tsx, apps/app/src/inngest/walletPortfolioSet.ts, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma
- fix: prisma wallet port
- feat: ini wallet prisma
- perf: ini token price
=> chore: ini prisma

apps/app/src/inngest/walletPortfolioSet.ts, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma
- fix: ini schema
- chore: ini schema
=> fix: ini schema v3

apps/app/app/(wallet)/[address]/(components)/PortfolioChart.tsx, apps/app/app/(wallet)/[address]/page.tsx, crates/axum/src/api.rs, crates/axum/src/routes/mod.rs, crates/axum/src/routes/portfolio.rs, crates/axum/src/routes/token.rs, crates/axum/src/routes/token_price.rs, packages/schemas/.depcheckrc.yml
- fix: tremore dashboard
- fix: portfolio page
=> fix: port dashboard

apps/app/app/(wallet)/[address]/overview/(components)/WalletOverviewBannerSparkline.tsx, crates/axum/src/routes/portfolio.rs, crates/axum/src/routes/token_price.rs, packages/client/src/v1.d.ts
- feat: ini update price
- perf: ini spark
=> feat: ini port

apps/app/src/inngest/walletPortfolioCovalentSet.ts, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma
=> chore: ini balance spam

crates/solutions/tests/it/builder.rs, crates/solutions/tests/it/main.rs, crates/solutions/tests/it/snapshots/it__builder__0-config.snap, crates/solutions/tests/it/snapshots/it__builder__0-new-config.snap
- fix: ini new builder config
- chore: ini buil
=> chore: ini b

crates/db/src/db.rs
- fix: db upsert
- feat: ini tx hash
=> fix: db upser

apps/app/app/(authenticated)/new/(components)/root-link.tsx, apps/app/src/components/tabs-nav.tsx, apps/app/src/components/wallet-switcher.tsx, apps/ui/src/components/ui/card.tsx, apps/ui/src/components/ui/table.tsx
- fix: bg weak for root link
- fix: command input transparent
- fix: card border
- fix: tabs nav
- fix: table border
=> fix: app styles

apps/app/app/(authenticated)/new/configuration/configuration-form.tsx, apps/app/app/(wallet)/[address]/owners/(components)/columns.tsx, apps/app/app/(wallet)/[address]/owners/(components)/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/owners/(components)/data-table.tsx, apps/app/src/const/configuration.ts
- fix: table styles
- fix: avatar orb
=> fix: table stles

apps/app/src/inngest/walletPortfolioCovalentSet.ts, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma
=> feat: ini balance wallet testnet

apps/app/app/(authenticated)/new/(hooks)/useOwnersQueryState.ts, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, apps/app/app/(wallet)/[address]/send/(hooks)/index.ts, apps/app/app/(wallet)/[address]/send/(hooks)/useTransfersQueryState.ts, apps/app/src/components/command-k.tsx, apps/app/src/schemas/index.ts, apps/app/src/schemas/sendForm.ts
- feat: rename transfers
- fix: transfer
- fix: parse address
=> feat: ini transfers

Cargo.lock, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/routes/user_operation.rs, crates/db/Cargo.toml, crates/db/src/db.rs
=> fix: prisma uop

configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/routes/user_operation.rs, crates/contracts/src/paymaster.rs, crates/contracts/src/provider.rs, crates/db/src/db.rs, crates/paymaster/src/paymaster.rs
=> feat: ini pm os

configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/routes/user_operation.rs, crates/db/src/db.rs, crates/polling/src/polling.rs
- chore: upsert db
- chore: ini update handler
=> chore: upsert tx

apps/app/app/(wallet)/[address]/@op/(.)op/page.tsx, apps/app/app/(wallet)/[address]/op/(components)/op-confirm-dialog.tsx, apps/app/app/(wallet)/[address]/op/(components)/op-create-card.tsx, apps/app/app/(wallet)/[address]/op/(components)/op-create-dialog.tsx, apps/app/app/(wallet)/[address]/op/page.tsx, apps/app/src/components/nav/main-nav.tsx, crates/axum/src/routes/user_operation.rs, crates/rpc/src/constants.rs
- fix: confirm2create
- fix: op update
=> fix: op routing

configurations/prisma/migrations/update_user_operation_status.sql, crates/axum/src/routes/user_operation.rs, crates/contracts/src/constants.rs, crates/db/src/db.rs
- feat: status update
- fix: testnet status
=> fix: status chains

apps/app/.env.production, apps/auth/next.config.mjs, apps/explorer/.env.production, apps/playground/.env.production
=> chore: update next

apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner.tsx, apps/app/package.json, apps/app/src/components/auth/auth-modal.tsx, apps/app/src/components/modal.tsx, apps/app/src/components/root/root.tsx, apps/app/src/data/nonce.ts, apps/app/src/queries/index.ts, apps/app/src/queries/nonce.ts, apps/app/src/stores/useModals.ts, apps/ui/index.tsx, apps/ui/src/components/ui/command.tsx, apps/ui/src/components/ui/dialog.stories.tsx, apps/ui/src/components/ui/dialog.tsx, crates/axum/src/api.rs, crates/axum/src/routes/wallet.rs, packages/client/src/index.ts, packages/client/src/v1.d.ts, pnpm-lock.yaml
- feat: ini auth modal
- feat: refactor dialog portal
=> feat: ini auth modal

crates/axum/src/api.rs, crates/axum/src/routes/auth.rs, packages/client/src/v1.d.ts
=> fix: api session

crates/axum/src/api.rs, crates/tracing/src/lib.rs, packages/client/src/index.ts
=> feat: ini w/ cors

apps/app/app/(wallet)/[address]/activity/(components)/activity-list.tsx, apps/app/app/(wallet)/[address]/overview/(components)/portfolio-chart.tsx, apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner-sparkline.tsx, apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner.tsx, apps/app/app/(wallet)/[address]/owners/(components)/owners-data-table.tsx, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, apps/app/app/(wallet)/[address]/settings/(components)/settings-deployment-card.tsx, apps/app/app/(wallet)/[address]/settings/(components)/settings-name-card.tsx, apps/app/app/(wallet)/[address]/settings/(components)/settings-testnet-card.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/user-operation/user-operations-list.tsx, apps/app/src/components/auth/auth-modal.tsx, apps/app/src/components/auth/auth-state.tsx, apps/app/src/components/nft/nfts-list.tsx, apps/app/src/components/token/token-card-sparkline.tsx, apps/app/src/components/token/tokens-list.tsx, apps/app/src/components/web3/wallet-switcher.tsx, apps/app/src/hooks/useDebouncedValue.ts, apps/app/src/hooks/useDelayedValue.ts, apps/app/src/hooks/useTabs.ts, apps/app/src/stores/useAuth.ts, apps/ui/src/components/ui/button.tsx, crates/axum/src/routes/auth.rs, packages/client/src/index.ts
- fix: update name
- chore: update button
- chore: ini banner overview
=> fix: name update

.release-it.json, apps/changelog/app/changelog.mdx, package.json, scripts/ts/changelog.ts, tsconfig.json
=> fix: root changelog

CHANGELOG.md, apps/changelog/app/changelog.mdx
=> chore: bun changes

.changeset/healthy-eagles-build.md, .changeset/pre.json, .github/workflows/release.yml, .release-it.json, scripts/ts/changelog.ts
=> chore: update bot

.changeset/flat-pets-film.md, .changeset/purple-rivers-flash.md, CHANGELOG.md, apps/app/app/(authenticated)/wallets/(components)/data-table/columns.tsx, apps/app/app/(authenticated)/wallets/(components)/data-table/data-table-column-header.tsx, apps/app/app/(authenticated)/wallets/(components)/data-table/data-table-faceted-filter.tsx, apps/app/app/(authenticated)/wallets/(components)/data-table/data-table-row-actions.tsx, apps/app/app/(authenticated)/wallets/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(authenticated)/wallets/(components)/data-table/data-table-view-options.tsx, apps/app/app/(authenticated)/wallets/(components)/data-table/data-table.tsx, apps/app/app/(authenticated)/wallets/(components)/nav-layout-bar.tsx, apps/app/app/(authenticated)/wallets/(components)/wallets-data-table.tsx, apps/app/app/(authenticated)/wallets/layout.tsx, apps/app/src/const/titles.ts, apps/app/src/stores/useTables.ts, scripts/py/copy_root_changeset.py
- feat: ini wallets list table
- fix: next router
=> feat: ini wallets

.github/workflows/release.yml, apps/app/app/(wallet)/[address]/overview/history/(components)/data-table/columns.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/data-table/data-table-column-header.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/data-table/data-table-faceted-filter.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/data-table/data-table-row-actions.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/data-table/data-table-view-options.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/data-table/data-table.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/history-data-table.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/nav-layout-bar.tsx, apps/app/app/(wallet)/[address]/overview/history/page.tsx, apps/app/src/stores/useTables.ts, apps/app/src/utils/chain.ts
- feat: ini history data table
- fix: owner table columns
=> feat: ini history data table

.github/workflows/node.yml, turbo.json
=> fix: release etc

apps/app/app/(authenticated)/wallets/(components)/data-table/data-table.tsx, fly/gas/fly.toml, turbo.json
- fix: turbo run input
- fix: table commit
=> fix: settings deployment

apps/app/app/(authenticated)/new/(components)/root/root-context.tsx, apps/ui/src/components/ui/badge.stories.tsx
https://ui.light.so?path=/docs/ui-badge--docs
cc: @fiveoutofnine - thank you.
=> fix: badge inverse text color

apps/app/app/(wallet)/[address]/overview/(components)/overview/overview-list.tsx, apps/app/src/components/nft/nfts-list.tsx, apps/app/src/components/token/tokens-list.tsx, apps/app/src/components/transaction/transactions-list.tsx, apps/app/src/handlers/paths/[address]/overview/handler.ts, apps/app/src/params/nft.ts, apps/app/src/services/getNfts.ts, packages/client/src/index.ts, packages/client/test/simplehash.spec.ts
=> fix: nft fetching client w/ ovverview list handler

apps/app/app/(authenticated)/new/(components)/root/root-context.tsx, apps/app/app/(wallet)/[address]/overview/(components)/invoke-portfolio-button.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/invoke-user-operation-button.tsx, apps/app/src/components/token/token-card-actions.tsx, apps/app/src/components/token/token-card-price.tsx, apps/app/src/components/token/token-card-token.tsx, apps/ui/src/components/ui/alert-dialog.tsx, apps/ui/src/components/ui/alert.stories.tsx, apps/ui/src/components/ui/alert.tsx, apps/ui/src/components/ui/badge.stories.tsx, apps/ui/src/components/ui/badge.tsx, apps/ui/src/components/ui/button.stories.tsx, apps/ui/src/components/ui/button.tsx, apps/ui/src/components/ui/dialog.tsx, apps/ui/src/components/ui/number.tsx, apps/ui/src/components/ui/sheet.tsx, apps/ui/src/components/ui/toast.tsx
> // Heavily inspired by the button primitives introduced by @fiveoutofnine
// Site: https://www.fiveoutofnine.com/design/component/button
// Code: https://github.com/fiveoutofnine/www/blob/a04dd54f76f57c145155dce96744d003f0d3de5e/components/ui/button/styles.tsx
// License: MIT
To be deployed on https://ui.light.so/?path=/docs/ui-badge--docs & https://ui.light.so/?path=/docs/ui-button--docs correspondly
=> feat: ini 5/9 design primitives (button, badge)

apps/ui/src/components/ui/button.tsx, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, configurations/styles/global.css, configurations/tailwindcss/src/index.js
- feat: ini timestamp user op schema
- fix: updated at default
=> feat: ini updated at schema

.github/workflows/node.yml, apps/app/app/(wallet)/[address]/op/(components)/op-create-card.tsx
=> fix: linting

apps/app/app/(wallet)/[address]/settings/(components)/settings-deployment-card.tsx, apps/app/app/(wallet)/[address]/settings/deployment/page.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/transactions-data-table.tsx, apps/app/app/(wallet)/[address]/transactions/@nav/all/page.tsx, apps/app/app/(wallet)/[address]/transactions/@nav/history/page.tsx, apps/app/app/(wallet)/[address]/transactions/history/page.tsx, apps/app/app/(wallet)/[address]/transactions/page.tsx, apps/app/src/components/command-k.tsx, apps/app/src/handlers/paths/[address]/settings/deployment/handler.ts, apps/app/src/handlers/paths/[address]/transactions/handler.ts, apps/app/src/handlers/paths/[address]/transactions/history/handler.ts, apps/app/src/params/userOperation.ts, apps/app/src/preloaders/paths/[address]/settings/deployment/preloader.ts, apps/app/src/preloaders/paths/[address]/transactions/history/preloader.ts, apps/app/src/preloaders/paths/[address]/transactions/preloader.ts, apps/app/src/services/getUserOperations.ts, apps/app/src/services/getUserOperationsCount.ts, crates/axum/src/routes/user_operation/list.rs, packages/client/src/index.ts, packages/client/src/v1.d.ts
- feat: ini history query
- feat: ini handlers update query history
=> feat: ini op history query

Cargo.lock, apps/app/src/components/nav/user-nav.tsx, apps/app/src/components/section/banner-section.tsx, bin/src/bin/consumer.rs, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/consumer/Cargo.toml, crates/consumer/src/config.rs, crates/consumer/src/consumer.rs, crates/consumer/src/topics/activity.rs, crates/consumer/src/topics/error_transaction.rs, crates/consumer/src/topics/mod.rs, crates/consumer/src/topics/notification.rs, crates/consumer/src/topics/transaction.rs, crates/consumer/src/topics/unknown.rs, crates/kafka/src/namespace.rs
- feat: ini category action
- feat: app bin hook
=> feat: ini category action

configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma
- chore: add comments
- fix: linting
=> feat: refactor prisma schema

Cargo.lock, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/db/Cargo.toml, crates/db/src/db.rs
=> feat: ini activity db log

apps/app/app/(authenticated)/wallets/(components)/data-table/data-table.tsx, apps/app/app/(unauthenticated)/(components)/root-welcome-cards.tsx, apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner/wallet-overview-banner-address.tsx, apps/app/app/(wallet)/[address]/owners/(components)/data-table/data-table.tsx, apps/app/app/(wallet)/[address]/owners/(components)/owners-data-table.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/data-table/columns.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/data-table/data-table.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/transaction/transaction-card.tsx, apps/app/src/components/data-table/data-table-faceted-filter.tsx, apps/app/src/components/settings/settings-card.tsx, apps/app/src/components/user-operation/user-operation-timeline.tsx, apps/app/src/components/web3/connect-button.tsx, apps/app/src/hooks/useTabs.ts, apps/ui/src/components/ui/timeline.tsx, packages/utils/src/index.ts, packages/utils/src/shorten.ts
=> feat: ini styling

.github/workflows/contracts.yml, crates/axum/src/api.rs
- feat: ini cookie domain
- chore: update api cookie
- chore: ini sid name
=> chore: ini cookie sid name

Cargo.lock, Cargo.toml, crates/consumer/src/consumer.rs, crates/consumer/src/topics/covalent.rs, crates/covalent/Cargo.toml, crates/covalent/src/constants.rs, crates/covalent/src/lib.rs, crates/covalent/src/types.rs, crates/covalent/tests/it/main.rs, crates/covalent/tests/it/test.rs, crates/kafka/src/namespace.rs
- feat: ini covalent crate
- chore: ini pagination types
- feat: ini covalent crate
=> feat: ini covalent crate

.github/workflows/fly.yml, Cargo.lock, crates/axum/src/routes/wallet/create.rs, crates/axum/src/routes/wallet/update.rs, crates/consumer/src/topics/activity.rs, crates/consumer/src/topics/covalent.rs, crates/db/src/models/activity.rs, crates/kafka/Cargo.toml, crates/kafka/src/lib.rs, crates/kafka/src/topics/covalent.rs, crates/kafka/src/topics/mod.rs, crates/kafka/src/traits.rs, crates/kafka/src/types/activity.rs, crates/kafka/src/types/covalent.rs, crates/kafka/src/types/mod.rs, fly/consumer-cvalnt/fly.toml
- feat: ini kafka topics
- chore: ini cvalnt ocnsumer
=> feat: ini cvalnt crate

.github/workflows/contracts.yml, crates/consumer/src/consumer.rs, crates/consumer/src/topics/covalent.rs, crates/consumer/src/topics/portfolio.rs, crates/kafka/src/topics/portfolio.rs
- feat: ini portfolio consumer
=> fix: consumer prtflo

apps/app/app/(authenticated)/new/(components)/new-wallet-form.tsx, apps/app/app/(authenticated)/new/configuration/(components)/configuration-form.tsx, apps/app/app/(authenticated)/new/confirm/(components)/confirm-form.tsx, apps/app/app/(authenticated)/settings/(components)/settings-appearance-card.tsx, apps/app/app/(authenticated)/settings/(components)/settings-notification-card.tsx, apps/app/app/(authenticated)/settings/(components)/settings-profile-card.tsx, apps/app/app/(authenticated)/wallets/(components)/wallets-data-table.tsx, apps/app/app/(wallet)/[address]/activity/(components)/activity-data-table.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/history-data-table.tsx, apps/app/app/(wallet)/[address]/overview/tokens/(components)/tokens-data-table.tsx, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, apps/app/app/(wallet)/[address]/settings/(components)/settings-name-card.tsx, apps/app/app/(wallet)/[address]/settings/(components)/settings-testnet-card.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/transactions-data-table.tsx, apps/app/src/components/feedback/feedback-form.tsx, apps/app/src/schemas/newForm.ts
- fix: ini empty table
- feat: ini mode blur for useForm
=> fix: empty table

.github/workflows/changesets.yml, apps/app/app/(authenticated)/new/configuration/(components)/configuration-form.tsx, apps/app/app/(authenticated)/new/confirm/(components)/confirm-form.tsx, apps/app/app/(wallet)/[address]/overview/(components)/overview/overview-invoke-button.tsx, apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner/wallet-overview-banner-address.tsx, apps/app/app/(wallet)/[address]/overview/layout.tsx, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/data-table/columns.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/overview/overview-invoke-button.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/transaction/transaction-card.tsx, apps/app/app/(wallet)/[address]/transactions/layout.tsx, apps/app/src/components/token/token-card-actions.tsx, apps/ui/src/components/ui/button-icon.tsx, apps/ui/src/components/ui/button.tsx, apps/ui/src/components/ui/carousel.tsx
- chore: ini refactor
- fix: validate
=> chore: ini button icon

crates/axum/src/routes/token/get.rs, crates/axum/src/routes/token/list.rs, crates/axum/src/routes/token/types.rs
=> fix: token group

apps/app/app/(wallet)/[address]/overview/tokens/(components)/data-table/data-table.tsx, apps/app/src/components/chain/chain-popover.tsx, apps/app/src/components/feedback/feedback-form.tsx, apps/app/src/components/section/link-button-group.tsx, apps/app/src/components/token/tokens-list.tsx, apps/ui/src/components/ui/button-group.tsx, apps/ui/src/components/ui/button.tsx
- fix: chain popover
- chore: update feedback form
=> fix: chain misc

configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma
=> chore: refactor prisma

apps/app/src/components/section/link-button-group.tsx, apps/ui/index.tsx, apps/ui/src/components/ui/badge.tsx, apps/ui/src/components/ui/form.tsx, apps/ui/src/components/ui/tabs.stories.tsx, apps/ui/src/components/ui/tabs.tsx, apps/ui/src/components/ui/toast.stories.tsx, apps/ui/src/components/ui/toast.tsx, apps/ui/src/components/ui/toggle.stories.tsx, apps/ui/src/components/ui/tooltip.stories.tsx, apps/ui/src/components/ui/tooltip.tsx
- chore: refactor button group props
- chore: ini arrow tooltip
- feat: ini tab outline
- chore: ini fix tab
=> chore: ini tab groups

.changeset/config.json, .github/workflows/changesets.yml, package.json
=> fix: push v2

.github/workflows/changesets.yml
- fix: term
- fix: token props
=> fix: token perm v2

apps/app/app/(authenticated)/new/(components)/new-wallet-form.tsx, apps/app/app/(authenticated)/new/(components)/root/root-link.tsx, apps/app/app/(authenticated)/new/configuration/(components)/configuration-form.tsx, apps/ui/index.tsx, apps/ui/package.json, apps/ui/src/components/ui/otp.stories.tsx, apps/ui/src/components/ui/otp.tsx, packages/client/package.json, packages/const/package.json, packages/schemas/package.json, packages/utils/package.json
- feat: ini ui package otop
- fix: new wallet otp
- fix: form configuration trigger
- fix: otp paste
- fix: code
- fix: code validation
=> feat: ini otp

bin/src/bin/consumer.rs, bin/src/bin/indexer.rs, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/api.rs, crates/axum/src/error.rs, crates/axum/src/lib.rs, crates/axum/src/routes/interpretation/error.rs, crates/axum/src/routes/interpretation/get.rs, crates/axum/src/routes/interpretation/list.rs, crates/axum/src/routes/interpretation/mod.rs, crates/axum/src/routes/interpretation/types.rs, crates/axum/src/routes/interpretation/update.rs, crates/axum/src/routes/mod.rs, crates/consumer/src/lib.rs, crates/prisma/src/main.rs, scripts/add_recursive_flag.sh
- chore: udpate default strat
- feat: ini interpretation ahndler
=> fix: ini interpretation

.changeset/wise-lizards-juggle.md, .github/workflows/fly.yml, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/routes/user_operation/create.rs, crates/db/src/models/user_operation.rs, crates/interpreter/tests/it/eth_transfer.rs, crates/kafka/src/namespace.rs, crates/paymaster/src/lib.rs, fly/consumer-actvty/fly.toml, fly/consumer-cvalnt/fly.toml, fly/consumer-error/fly.toml, fly/consumer-intptn/fly.toml, fly/consumer-prtflo/fly.toml
=> feat: ini consumer intptn

.changeset/odd-monkeys-knock.md, apps/app/app/(wallet)/[address]/settings/(components)/settings-name-card.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/transaction/transaction-card-execute-button.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/transaction/transaction-card-sign-button.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/transaction/transaction-card.tsx, apps/app/app/(wallet)/[address]/transactions/(hooks)/useUserOperationSign.ts, apps/app/app/(wallet)/[address]/transactions/(hooks)/useUserOperationSubmit.ts, apps/app/src/components/web3/connect-button.tsx, apps/ui/src/components/ui/button.stories.tsx, apps/ui/src/components/ui/button.tsx, packages/client/src/api/index.ts, packages/client/src/api/signature.ts
- chore: update flag cards
- fix: card txs
=> fix: tx cards

configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/routes/signature/create.rs, crates/axum/src/routes/support_request/create.rs, crates/axum/src/routes/user_operation/create.rs, crates/axum/src/routes/wallet/create.rs, crates/axum/src/routes/wallet/update.rs, crates/consumer/src/topics/activity.rs
=> fix: activity ops

.changeset/loud-starfishes-return.md, apps/app/app/(wallet)/[address]/op/(components)/op-create-card.tsx, apps/app/app/(wallet)/[address]/transactions/(hooks)/useUserOperationCreate.ts, apps/ui/src/components/ui/otp.tsx, crates/axum/src/routes/signature/create.rs, crates/axum/src/routes/signature/get.rs, crates/axum/src/routes/user_operation/create.rs, packages/client/src/v1.d.ts
- fix: op create
- chore: crate update
=> fix: op create

apps/app/app/(wallet)/[address]/op/(components)/op-create-card.tsx, apps/ui/src/templates/footer/footer-list.tsx, apps/ui/src/templates/footer/footer-social.tsx
- fix: create card fix
- chore: update list
=> fix: session create

crates/axum/src/routes/user_operation/create.rs, fly/polling-live/fly.toml, fly/polling-past/fly.toml, fly/polling/fly.toml
- fix: polling config
- fix: ini sig create log
=> fix: polling live

apps/app/app/api/edge-flags/route.ts, apps/app/middleware.ts, apps/app/package.json, apps/app/src/clients/redis.ts, apps/app/src/components/chain/chain-popover.tsx, apps/app/src/hooks/useDelayedValue.ts, apps/app/src/hooks/useEdgeFlag.ts, apps/app/src/hooks/useMediaQuery.ts, apps/app/src/hooks/useTabs.ts, apps/app/src/hooks/useTabs.tsx, apps/app/src/query/index.ts, apps/app/src/query/useSuspenseQueryConfiguration.ts, pnpm-lock.yaml
- feat: ini edge flags
- fix: edge flags
=> feat: ini edge flags

apps/app/app/(authenticated)/new/(components)/new-wallet-form.tsx, apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner/wallet-overview-banner.tsx, apps/app/src/components/lightdotso/light-logo.tsx, apps/app/src/components/lightdotso/placeholder-orb.tsx, apps/app/src/components/nav/app-nav.tsx, apps/app/src/components/nav/main-nav.tsx, apps/app/src/components/nav/tabs-nav.tsx, apps/app/src/components/root/root.tsx, apps/ui/src/components/ui/command.tsx, apps/ui/src/components/ui/drawer.tsx, apps/ui/src/components/ui/otp.tsx, apps/ui/src/components/ui/table.tsx, apps/ui/src/templates/footer/footer-list.tsx, apps/ui/src/templates/footer/footer.tsx
- feat: ini app nav
- fix: command input styling
- chore: update ui template
- fix: drawer dialog overlay styles
- fix: wallet nav fix
=> fix: nav ui

apps/app/package.json, apps/app/src/components/nav/app-nav.tsx, apps/changelog/.depcheckrc.yml, apps/changelog/package.json, packages/const/.depcheckrc.yml, packages/const/package.json, pnpm-lock.yaml
- chore: refactor changelog clsx
- fix: app nav
=> fix: op explorer

.changeset/forty-monkeys-fold.md, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/db/src/db.rs, crates/db/src/models/interpretation.rs, crates/db/tests/it/transaction.rs, crates/db/tests/it/user_operation.rs, crates/interpreter/src/adapters/transfer/erc1155.rs, crates/interpreter/src/adapters/transfer/erc20.rs, crates/interpreter/src/adapters/transfer/erc721.rs, crates/interpreter/src/adapters/transfer/eth.rs, crates/interpreter/src/types.rs, crates/interpreter/tests/it/transfer/snapshots/it__transfer__erc1155_transfer__integration_erc1155_transfer.snap, crates/interpreter/tests/it/transfer/snapshots/it__transfer__erc20_transfer__integration_erc20_transfer.snap, crates/interpreter/tests/it/transfer/snapshots/it__transfer__erc721_transfer__integration_erc721_mint.snap, crates/interpreter/tests/it/transfer/snapshots/it__transfer__erc721_transfer__integration_erc721_transfer.snap, crates/interpreter/tests/it/transfer/snapshots/it__transfer__eth_transfer__integration_eth_transfer.snap, crates/interpreter/tests/it/transfer/snapshots/it__transfer__eth_transfer__integration_light_eth_transfer.snap
- fix: ini db test integration
=> fix: db client test

.changeset/famous-walls-brush.md, .github/workflows/rust.yml, Cargo.lock, crates/db/Cargo.toml, crates/db/src/models/interpretation.rs, crates/db/tests/it/interpretation.rs, crates/db/tests/it/main.rs
=> fix: interpretation db

crates/db/src/models/interpretation.rs, crates/db/tests/it/interpretation.rs, crates/interpreter/src/adapters/transfer/erc1155.rs, crates/interpreter/src/adapters/transfer/erc20.rs, crates/interpreter/src/adapters/transfer/erc721.rs, crates/interpreter/src/adapters/transfer/eth.rs, crates/interpreter/src/types.rs, crates/interpreter/tests/it/transfer/snapshots/it__transfer__erc1155_transfer__integration_erc1155_transfer.snap, crates/interpreter/tests/it/transfer/snapshots/it__transfer__erc20_transfer__integration_erc20_transfer.snap, crates/interpreter/tests/it/transfer/snapshots/it__transfer__erc721_transfer__integration_erc721_mint.snap, crates/interpreter/tests/it/transfer/snapshots/it__transfer__erc721_transfer__integration_erc721_transfer.snap, crates/interpreter/tests/it/transfer/snapshots/it__transfer__eth_transfer__integration_eth_transfer.snap, crates/interpreter/tests/it/transfer/snapshots/it__transfer__eth_transfer__integration_light_eth_transfer.snap
- feat: ini token interpretation token type
- chore: update interpretation
=> fix: intepretation token flow

.changeset/nice-bobcats-sneeze.md, Cargo.lock, crates/axum/src/routes/simulation/create.rs, crates/simulator/Cargo.toml, crates/simulator/src/simulator.rs, packages/client/src/types/api/v1.d.ts
=> fix: simulator ops

.changeset/eleven-meals-compare.md, Dockerfile, configurations/prisma/migrations/delete_unchecksum_token.sql, crates/consumer/src/topics/covalent.rs
=> fix: ini sql prob

.changeset/sixty-maps-turn.md, apps/app/src/components/web3/wallet-switcher.tsx, apps/app/src/hooks/usePathType.ts, packages/table/src/notification/notification-table.tsx, packages/table/src/table-empty.tsx
=> feat: ini modal stack

.changeset/itchy-baboons-obey.md, Cargo.lock, Cargo.toml, crates/axum/src/api.rs, crates/opentelemetry/Cargo.toml, crates/opentelemetry/src/lib.rs, crates/opentelemetry/src/middleware.rs, fly/api/fly.toml
- feat: ini axum cargo
- chore: update fly middleware
=> feat: ini otlp middleware

.changeset/perfect-crews-smile.md, apps/app/app/(authenticated)/new/(components)/new-wallet-form.tsx, apps/app/app/(authenticated)/new/configuration/(components)/configuration-form.tsx, apps/app/app/(authenticated)/new/confirm/(components)/confirm-form.tsx, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, apps/app/src/hooks/usePathType.ts, packages/elements/src/token-image.tsx, packages/hooks/src/useUserOperationCreate.ts, packages/templates/src/modal/modal.tsx
- fix: button child
- chore: ini send dialog
- fix: transfer dialog styling
- fix: changeset clearance
=> feat: ini button table

.changeset/silent-nails-wash.md, apps/app/app/(wallet)/[address]/settings/(components)/settings-testnet-card.tsx, crates/axum/src/admin.rs, crates/axum/src/auth.rs, crates/axum/src/authentication.rs, crates/axum/src/lib.rs, crates/axum/src/routes/activity/list.rs, crates/axum/src/routes/invite_code/list.rs, crates/axum/src/routes/notification/list.rs, crates/axum/src/routes/wallet/update.rs, crates/axum/src/routes/wallet_settings/update.rs
- feat: ini invite code list params
- feat: refactor authentication
- chore: update authentication activity
- feat: ini notification list
=> feat: ini auth list

packages/tables/src/(components)/card/address-card.tsx, packages/tables/src/(components)/card/interpretation-card.tsx, packages/tables/src/owner/owner-table.tsx, packages/tables/src/wallet/card/index.ts, packages/tables/src/wallet/card/wallet-card-address.tsx, packages/tables/src/wallet/wallet-columns.tsx
- chore: ini address card
- chore: update table address
=> feat: ini table complete

.changeset/old-sheep-drum.md, apps/app/app/(authenticated)/notifications/(components)/notifications-data-table-pagination.tsx, apps/app/app/(authenticated)/notifications/(components)/notifications-data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/activity/(components)/activity-data-table-pagination.tsx, apps/app/app/(wallet)/[address]/activity/(components)/activity-data-table-toolbar.tsx, apps/app/src/components/nav/user-nav.tsx
=> fix: ini log out

crates/axum/src/routes/auth/mod.rs, crates/axum/src/routes/auth/types.rs, packages/tables/src/token/token-columns.tsx
- feat: ini refactor token columns
- chore: update auth
=> fix: ini footer

apps/app/app/(wallet)/[address]/activity/layout.tsx, apps/app/app/(wallet)/[address]/op/[userOperationHash]/page.tsx, packages/tables/src/(components)/card/interpretation-action-card.tsx
- fix: layout page
- fix: ini fix padding
=> feat: ini op transition

.changeset/chatty-cooks-fetch.md, apps/app/src/components/nav/main-nav.tsx, apps/app/src/components/nav/tabs-nav.tsx, crates/axum/src/routes/simulation/create.rs
- test: fix tabs link
- fix: tabs
=> fix: ini tabs

.changeset/four-waves-rescue.md, apps/app/app/(wallet)/@op/(.)[address]/op/(components)/modal-interception-footer.tsx, apps/app/app/(wallet)/@op/(.)[address]/op/page.tsx, apps/app/app/(wallet)/[address]/op/(components)/op-transaction.tsx, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, packages/const/src/index.ts, packages/const/src/pagination.ts, packages/hooks/src/useAuthModal.ts, packages/hooks/src/useUserOperationCreate.ts, packages/nuqs/package.json, packages/nuqs/src/index.ts, packages/nuqs/src/usePaginationQueryState.ts, packages/nuqs/src/useTransfersQueryState.ts, packages/nuqs/src/useUserOperationsIndexQueryState.ts, packages/nuqs/src/useUserOperationsQueryState.ts, packages/schemas/src/form/index.ts, packages/schemas/src/form/sendForm.ts, packages/schemas/src/index.ts, packages/tables/src/user-operation/card/user-operation-card-transaction-execute-button.tsx, packages/tables/src/user-operation/card/user-operation-card-transaction-sign-button.tsx, packages/templates/src/data-table/data-table-pagination.tsx, packages/templates/src/login/login.tsx, packages/templates/src/transaction/transaction.tsx, pnpm-lock.yaml
- feat: ini login tx
- feat: ini op schemes
=> chore: refactor fetch

.changeset/funny-points-wait.md, apps/app/app/(wallet)/[address]/op/(components)/op-transaction.tsx, apps/app/src/handlers/paths/[address]/op/handler.ts, crates/rpc/src/constants.rs, packages/client/src/rpc/index.ts, packages/query-keys/src/index.ts, packages/query-keys/src/rpc.ts, packages/query/src/index.ts, packages/query/src/useQueryEstimateUserOperationGas.ts, packages/templates/src/transaction/transaction.tsx
- feat: ini op estimate uop
- chore: ini estimate uop
=> feat: ini estimate uop

.github/workflows/python.yml, crates/axum/src/rpc.rs, packages/query/src/useQueryEstimateUserOperationGas.ts, thunder-tests/collections/tc_col_rpclightso.json
=> fix: ini govern builder

.changeset/brave-onions-impress.md, packages/const/src/social_links.ts, packages/hooks/src/useAuthModal.ts, packages/templates/src/banner/banner.tsx, packages/templates/src/transaction/transaction.tsx
- feat: refactor banner links
- chore: refactor changeset imprs
=> feat: refactor banner social

.github/workflows/fly.yml, apps/open/public/index.html, fly/metabase/fly.toml
=> feat: ini metabase open

.changeset/sixty-insects-work.md, apps/app/app/(wallet)/[address]/overview/(components)/overview/overview-invoke-button.tsx, apps/app/src/components/nav/user-nav.tsx, apps/app/src/components/root/root.tsx, crates/axum/src/routes/token/list.rs, packages/params/src/queue.ts, packages/query/.depcheckrc.yml, packages/query/src/useMutationQueuePortfolio.ts, packages/query/src/useMutationQueueToken.ts, packages/query/src/useMutationUserOperationSend.ts, packages/states/src/index.ts, packages/states/src/queue-state.tsx, packages/stores/src/index.ts, packages/stores/src/useQueues.ts, packages/stores/src/useTables.ts
- feat: ini invoke queue
- chore: update mutation
=> feat: ini queues

apps/app/app/(wallet)/[address]/settings/(components)/settings-name-card.tsx, apps/app/app/(wallet)/[address]/settings/(components)/settings-testnet-card.tsx, apps/app/src/components/feedback/feedback-form.tsx, packages/hooks/src/useSignInWithSiwe.tsx, packages/modals/src/auth/auth-modal.tsx, packages/query/src/useMutationAuthVerify.ts, packages/query/src/useMutationFeedbackCreate.ts, packages/query/src/useMutationQueuePortfolio.ts, packages/query/src/useMutationQueueToken.ts
=> fix: proper loading

crates/axum/src/routes/configuration/get.rs, crates/axum/src/routes/configuration/types.rs, crates/axum/src/routes/wallet_features/get.rs, crates/axum/src/routes/wallet_settings/get.rs, packages/query/src/useMutationQueuePortfolio.ts, packages/query/src/useMutationQueueToken.ts, packages/states/src/queue-state.tsx, packages/stores/src/useQueues.ts
- chore: update configuration create
- feat: ini address queue
=> chore: ini billing

.changeset/big-lizards-search.md, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/api.rs, crates/axum/src/error.rs, crates/axum/src/routes/mod.rs, crates/axum/src/routes/token/list.rs, crates/axum/src/routes/wallet_billing/error.rs, crates/axum/src/routes/wallet_billing/get.rs, crates/axum/src/routes/wallet_billing/mod.rs, crates/axum/src/routes/wallet_billing/types.rs, crates/axum/src/routes/wallet_billing/update.rs, packages/client/src/api/wallet_billing.ts, packages/client/src/types/api/v1.d.ts, packages/data/src/index.ts, packages/data/src/walletBilling.ts, packages/params/src/index.ts, packages/params/src/walletBilling.ts, packages/query/src/index.ts, packages/query/src/useQueryWalletBilling.ts
- feat: ini wallet billing
- feat: ini billing wallet
=> feat: ini wallet billing

apps/app/app/(wallet)/[address]/settings/billing/(components)/settings-billing-balance-card.tsx, apps/app/src/components/feedback/feedback-form.tsx, apps/storybook/.depcheckrc.yml, apps/storybook/.storybook/preview.tsx, apps/storybook/package.json, configurations/eslint/src/index.js, crates/axum/src/routes/token/list.rs, packages/const/src/api_urls.ts, packages/const/src/index.ts, packages/demo/src/api/simulation/create.json, packages/demo/src/api/simulation/index.ts, packages/demo/src/api/userOperation/index.ts, packages/demo/src/index.ts, packages/demo/src/rpc/index.ts, packages/demo/src/rpc/paymaster/estimateUserOperationGas.json, packages/demo/src/rpc/paymaster/index.ts, packages/demo/src/rpc/paymaster/paymasterAndData.json, packages/msw/src/handlers/index.ts, packages/msw/src/handlers/rpc.ts, packages/msw/src/handlers/simulation.ts, packages/msw/src/handlers/token_price.ts, packages/msw/src/handlers/wallet.ts, packages/templates/package.json, packages/templates/src/transaction/transaction-dev-info.tsx, packages/templates/src/transaction/transaction.stories.tsx, packages/templates/src/transaction/transaction.tsx, pnpm-lock.yaml
- chore: ini tx form
- fix: dev info
=> feat: ini sim tx

.changeset/modern-kangaroos-camp.md, crates/axum/src/routes/user_operation/create.rs, crates/consumer/src/topics/portfolio.rs, crates/db/src/models/interpretation.rs, crates/db/src/models/paymaster_operation.rs, crates/db/src/models/transaction.rs, crates/db/src/models/user_operation.rs, crates/package.json, pnpm-lock.yaml
- feat: refactor prisma chain model
=> chore: refactor chain prisma

.changeset/two-zoos-greet.md, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma
- feat: ini notifications schema
- chore: update schema
- chore: update schema changes
=> chore: ini wallet schema

crates/axum/src/api.rs, crates/axum/src/routes/queue/mod.rs, crates/axum/src/routes/queue/user_operation.rs, crates/consumer/src/consumer.rs, crates/consumer/src/topics/mod.rs, crates/consumer/src/topics/user_operation.rs, crates/graphql/src/polling/mod.rs, crates/graphql/src/polling/snapshots/lightdotso_graphql__polling__user_operation__test__snapshot_test_query.snap, crates/graphql/src/polling/user_operation.rs, crates/kafka/src/namespace.rs, crates/kafka/src/topics/mod.rs, crates/kafka/src/topics/user_operation.rs, crates/kafka/src/types/user_operation.rs, crates/redis/src/namespace.rs, crates/redis/src/query/mod.rs, crates/redis/src/query/user_operation.rs
- feat: ini graphql single query
- feat: ini kafka topic uop
- feat: ini uop queue ahndler
=> feat: ini uop hash

.changeset/silent-rice-visit.md, .github/workflows/fly.yml, Cargo.lock, crates/consumer/Cargo.toml, crates/consumer/src/consumer.rs, crates/consumer/src/topics/user_operation.rs, crates/graphql/src/polling/user_operations.rs, crates/polling/src/config.rs, crates/polling/src/polling.rs, fly/consumer-uop/fly.toml
- chore: ini fly uop
- chore: update changeset
=> chore: ini uop poll

.github/workflows/fly.yml, crates/consumer/src/consumer.rs, crates/consumer/src/topics/user_operation.rs, crates/polling/src/config.rs, crates/polling/src/polling.rs
- chore: update fly config
- chore: update polling op
- feat: ini polling ops
=> chore: ini queue op

apps/frames/app/page.tsx, apps/inngest/turbo.json, crates/consumer/src/topics/user_operation.rs, crates/kafka/src/types/user_operation.rs
- chore: ini op tests
- chore: ini page turbo
=> chore: ini op filter

.changeset/dry-turtles-rhyme.md, crates/db/src/models/transaction.rs, crates/db/tests/it/transaction.rs
- chore: update integration testing
- chore: update tx
=> chore: ini tx op

.changeset/purple-grapes-lick.md, Cargo.lock, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/routes/notification_settings/get.rs, crates/axum/src/routes/notification_settings/list.rs, crates/axum/src/routes/notification_settings/types.rs, crates/axum/src/routes/user_notification_settings/get.rs, crates/axum/src/routes/user_notification_settings/types.rs, crates/axum/src/routes/user_settings/get.rs, crates/axum/src/routes/wallet_features/get.rs, crates/axum/src/routes/wallet_notification_settings/get.rs, crates/axum/src/routes/wallet_notification_settings/types.rs, crates/axum/src/routes/wallet_notification_settings/update.rs, crates/axum/src/routes/wallet_settings/get.rs, crates/notifier/Cargo.toml, crates/polling/Cargo.toml, crates/polling/src/config.rs, crates/polling/src/constants.rs, crates/polling/src/polling.rs
- chore: notification settings typings
=> chore: ini notification settings

.changeset/healthy-countries-remember.md, Cargo.lock, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/Cargo.toml, crates/axum/src/api.rs, crates/axum/src/routes/notification_settings/types.rs, crates/axum/src/routes/user_notification_settings/get.rs, crates/axum/src/routes/user_notification_settings/types.rs, crates/axum/src/routes/user_notification_settings/update.rs, crates/axum/src/routes/wallet_notification_settings/get.rs, crates/axum/src/routes/wallet_notification_settings/types.rs, crates/axum/src/routes/wallet_notification_settings/update.rs, crates/notifier/Cargo.toml, crates/notifier/src/key.rs, crates/notifier/src/lib.rs, crates/notifier/src/snapshots/lightdotso_notifier__types__tests__NOTIFICATION.snap, crates/notifier/src/snapshots/lightdotso_notifier__types__tests__NOTIFICATION_DEFAULT_ENABLED.snap, crates/notifier/src/snapshots/lightdotso_notifier__types__tests__NOTIFICATION_DEFAULT_ENABLED.snap.new, crates/notifier/src/snapshots/lightdotso_notifier__types__tests__NOTIFICATION_KEYS.snap, crates/notifier/src/snapshots/lightdotso_notifier__types__tests__OPERATIONS.snap, crates/notifier/src/snapshots/lightdotso_notifier__types__tests__USER_NOTIFICATION_DEFAULT_ENABLED.snap, crates/notifier/src/snapshots/lightdotso_notifier__types__tests__USER_NOTIFICATION_KEYS.snap, crates/notifier/src/snapshots/lightdotso_notifier__types__tests__WALLET_NOTIFICATION_DEFAULT_ENABLED.snap, crates/notifier/src/snapshots/lightdotso_notifier__types__tests__WALLET_NOTIFICATION_KEYS.snap, crates/notifier/src/types.rs
=> chore: ini notifier

apps/app/app/(wallet)/[address]/settings/notifications/(components)/settings-notifications-settings-card.tsx, apps/app/app/(wallet)/[address]/settings/notifications/layout.tsx, apps/app/app/(wallet)/[address]/settings/notifications/page.tsx, apps/app/src/const/titles.ts, apps/app/src/handlers/paths/[address]/settings/notifications/handler.ts, crates/axum/src/routes/wallet_notification_settings/get.rs, packages/client/src/api/wallet_notification_settings.ts, packages/client/src/types/api/v1.d.ts, packages/data/src/activity.ts, packages/data/src/assetChange.ts, packages/data/src/billing.ts, packages/data/src/index.ts, packages/data/src/notificationSettings.ts, packages/data/src/token.ts, packages/data/src/transaction.ts, packages/data/src/userOperation.ts, packages/data/src/walletNotificationSettings.ts, packages/query-keys/src/wallet.ts, packages/query/src/index.ts, packages/query/src/useQueryWalletNotificationSettings.ts, packages/services/src/getWalletNotificationSettings.ts, packages/services/src/index.ts
- feat: ini notification settings
- feat: ini notification settings
=> feat: ini query nfn

.changeset/wet-countries-destroy.md, apps/app/app/(authenticated)/settings/(components)/settings-appearance-card.tsx, apps/app/app/(authenticated)/settings/(components)/settings-profile-card.tsx, apps/app/app/(authenticated)/settings/appearance/(components)/settings-appearance-card.tsx, apps/app/app/(authenticated)/settings/appearance/layout.tsx, apps/app/app/(authenticated)/settings/appearance/page.tsx, apps/app/app/(authenticated)/settings/layout.tsx, apps/app/app/(authenticated)/settings/notifications/(components)/settings-notification-card.tsx, apps/app/app/(authenticated)/settings/notifications/layout.tsx, apps/app/app/(authenticated)/settings/notifications/page.tsx, apps/app/app/(wallet)/[address]/settings/(components)/settings-name-card.tsx, apps/app/app/(wallet)/[address]/settings/(components)/settings-testnet-card.tsx, apps/app/app/(wallet)/[address]/settings/billing/(components)/settings-billing-balance-card.tsx, apps/app/app/(wallet)/[address]/settings/deployment/(components)/settings-deployment-card.tsx, apps/app/app/(wallet)/[address]/settings/deployment/layout.tsx, apps/app/app/(wallet)/[address]/settings/layout.tsx, apps/app/app/(wallet)/[address]/settings/notifications/(components)/settings-notifications-settings-card.tsx, apps/app/app/(wallet)/[address]/settings/notifications/layout.tsx, apps/app/src/const/titles.ts, apps/app/src/handlers/paths/[address]/settings/notifications/handler.ts, packages/data/src/walletBilling.ts, packages/data/src/walletNotificationSettings.ts, packages/params/src/walletSettings.ts
=> chore: ini app card

apps/app/app/(authenticated)/notifications/(components)/notifications-data-table.tsx, apps/app/app/(authenticated)/notifications/page.tsx, apps/app/src/components/nav/notifications-nav.tsx, apps/app/src/handlers/paths/notifications/handler.ts, crates/axum/src/routes/notification/list.rs, packages/nuqs/src/index.ts, packages/nuqs/src/useAddressQueryState.ts
- feat: ini notification query
- chore: ini nfn tab
=> chore: ini address query state

broadcast/PaymasterAddDepositOps.s.sol/42161/run-1707422138.json, broadcast/PaymasterAddDepositOps.s.sol/42161/run-1707422164.json, broadcast/PaymasterAddDepositOps.s.sol/42161/run-latest.json, broadcast/PaymasterAddDepositOps.s.sol/421614/run-1707420036.json, broadcast/PaymasterAddDepositOps.s.sol/421614/run-latest.json, broadcast/PaymasterAddStakeOps.s.sol/42161/run-1707422081.json, broadcast/PaymasterAddStakeOps.s.sol/42161/run-latest.json, broadcast/PaymasterAddStakeOps.s.sol/421614/run-1707419983.json, broadcast/PaymasterAddStakeOps.s.sol/421614/run-latest.json, packages/hooks/src/useUserOperationCreate.ts, packages/hooks/src/useUserOperationSubmit.ts, packages/params/src/userOperation.ts, packages/query/src/useMutationUserOperationCreate.ts, packages/query/src/useMutationUserOperationSend.ts, packages/query/src/useMutationWalletCreate.ts, packages/tables/src/notification/card/index.ts, packages/tables/src/notification/card/notification-card-address.tsx, packages/tables/src/notification/card/notification-card-entity.tsx, packages/tables/src/notification/card/notification-card-operation.tsx, packages/tables/src/notification/card/notification-card-timestamp.tsx, packages/tables/src/notification/notification-columns.tsx, packages/tables/src/user-operation/card/user-operation-card-transaction-execute-button.tsx
- chore: ini deploy query
- feat: ini table notification
=> chore: ini deploy query

.changeset/poor-socks-study.md, apps/app/src/components/nft/nfts-list.tsx, packages/tables/src/nft/nft-table.tsx, thunder-tests/collections/tc_col_rpclightso.json
- chore: ini nfts list limit
- chore: update api tc
=> chore: ini token nft modal

.changeset/funny-bags-shake.md, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/overview/overview-section-empty.tsx, apps/app/src/components/root/root.tsx, packages/elements/src/empty-state.stories.tsx, packages/elements/src/empty-state.tsx, packages/elements/src/index.ts, packages/modals/src/nft/nft-modal.stories.tsx, packages/modals/src/nft/nft-modal.tsx, packages/modals/src/token/token-modal.stories.tsx, packages/modals/src/token/token-modal.tsx, packages/query-keys/src/portfolio.ts, packages/stores/src/index.ts, packages/stores/src/useModals.ts, packages/tables/src/activity/activity-table.tsx, packages/tables/src/index.ts, packages/tables/src/nft/nft-table.tsx, packages/tables/src/notification/notification-table.tsx, packages/tables/src/owner/owner-table.tsx, packages/tables/src/token/token-table.tsx, packages/tables/src/transaction/transaction-table.tsx, packages/tables/src/user-operation/user-operation-table.tsx, packages/tables/src/wallet/wallet-table.tsx, packages/templates/src/modal/modal.tsx
- feat: ini send dialog modal
- feat: ini banner content
- feat: ini send token
=> feat: ini token modal

crates/contracts/src/constants.rs, crates/rpc/src/constants.rs, packages/const/src/chains.ts
=> chore: ini rpc urls

.changeset/afraid-berries-mix.md, crates/graphql/src/polling/snapshots/lightdotso_graphql__polling__user_operation__test__snapshot_test_query.snap, crates/kafka/src/types/user_operation.rs, crates/rpc/src/constants.rs, crates/rpc/src/lib.rs, packages/schemas/src/simplehash/nfts.ts
- chore: ini rpc url
- chore: ini constants
- chore: ini resp bundler
=> chore: ini bundle

.changeset/grumpy-cars-invent.md, apps/app/src/components/root/root.tsx, packages/modals/src/address/address-modal.stories.tsx, packages/modals/src/address/address-modal.tsx, packages/stores/src/index.ts, packages/stores/src/useModals.ts
=> chore: ini address modal

.changeset/smooth-peas-obey.md, Cargo.lock, crates/axum/src/routes/queue/user_operation.rs, crates/axum/src/rpc.rs, crates/consumer/src/consumer.rs, crates/consumer/src/topics/user_operation.rs, crates/kafka/src/types/user_operation.rs, crates/rpc/Cargo.toml, crates/rpc/src/lib.rs
- feat: ini uop queue
- chore: update smooth
=> feat: ini queue op

.changeset/orange-crabs-pull.md, apps/app/app/(wallet)/@send/(.)[address]/send/(components)/modal-interception-footer.tsx, apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner/wallet-overview-banner-address.tsx, apps/app/app/(wallet)/[address]/send/new/page.tsx, apps/app/app/(wallet)/[address]/send/redirect/page.tsx, crates/polling/src/polling.rs
- chore: ini banner addr
- fix: modal send
=> chore: ini toggle addr

.changeset/loud-wombats-nail.md, apps/app/app/(wallet)/@op/(.)[address]/op/(components)/modal-interception-footer.tsx, apps/app/app/(wallet)/@op/(.)[address]/op/[userOperationHash]/page.tsx, apps/app/app/(wallet)/[address]/op/[userOperationHash]/layout.tsx, apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner/wallet-overview-banner-sparkline.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/overview/overview-section.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/transactions-data-table.tsx, apps/app/app/(wallet)/[address]/transactions/@nav/queue/page.tsx, apps/app/app/(wallet)/[address]/transactions/page.tsx, apps/app/app/(wallet)/[address]/transactions/queue/page.tsx, apps/app/src/handlers/paths/[address]/transactions/handler.ts, apps/app/src/handlers/paths/[address]/transactions/queue/handler.ts, apps/app/src/hooks/useTabs.tsx, apps/app/src/preloaders/paths/[address]/transactions/preloader.ts, apps/app/src/preloaders/paths/[address]/transactions/queue/preloader.ts, apps/frames/app/api/frame/route.ts, crates/axum/src/routes/user_operation/list.rs, packages/client/src/api/user_operation.ts, packages/client/src/types/api/v1.d.ts, packages/params/src/userOperation.ts, packages/query/src/useMutationUserOperationCreate.ts, packages/query/src/useMutationUserOperationSend.ts
- feat: complete refactor queued
=> feat: ini queued

.changeset/five-eggs-raise.md, apps/app/app/(wallet)/@op/(.)[address]/op/(components)/modal-interception-footer.tsx, apps/app/app/(wallet)/@op/(.)[address]/op/[userOperationHash]/page.tsx, apps/app/app/(wallet)/[address]/create/(components)/create-transaction.tsx, apps/app/app/(wallet)/[address]/op/[userOperationHash]/(components)/op-invoke-button.tsx, apps/app/app/(wallet)/[address]/op/[userOperationHash]/layout.tsx, apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner/wallet-overview-banner-sparkline.tsx, apps/app/app/(wallet)/[address]/send/new/page.tsx, packages/elements/src/invoke-button.tsx, packages/query/src/useMutationUserOperationSend.ts
=> chore: ini queue handler

.changeset/olive-cobras-report.md, apps/app/app/(wallet)/[address]/dev/layout.tsx, apps/app/app/(wallet)/[address]/dev/page.tsx, apps/app/app/(wallet)/[address]/settings/(components)/settings-dev-card.tsx, apps/app/app/(wallet)/[address]/settings/page.tsx, apps/app/src/const/tabs.tsx, apps/app/src/const/titles.ts, apps/app/src/handlers/paths/[address]/dev/handler.ts, apps/app/src/handlers/paths/[address]/handler.ts, apps/app/src/hooks/useTabs.tsx, apps/app/src/preloaders/paths/[address]/dev/preloader.ts, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma, crates/axum/src/routes/wallet_settings/types.rs, packages/client/src/types/api/v1.d.ts, packages/data/src/walletSettings.ts, packages/params/src/walletSettings.ts
- feat: ini wallet settings dev
- feat: ini dev layout
=> feat: ini dev mode

crates/axum/src/routes/activity/types.rs, packages/tables/src/user-operation/card/user-operation-card-transaction.tsx, packages/templates/src/notification-popover/notification-popover.tsx, packages/templates/src/transaction/transaction-details-info.tsx, packages/templates/src/transaction/transaction.tsx
- chore: ini stores popover
- chore: ini tx op
=> fix: ini tx nfg

packages/templates/src/connect-button/connect-button.tsx, packages/templates/src/notification-popover/notification-popover-icon.tsx, packages/wagmi/src/config.ts
- fix: config transport
- fix: span
- fix: notification count
=> fix: notification count

.changeset/moody-jobs-fail.md, .github/workflows/fly.yml, Cargo.lock, crates/consumer/Cargo.toml, crates/consumer/src/consumer.rs, crates/consumer/src/topics/mod.rs, crates/consumer/src/topics/routescan.rs, crates/kafka/src/namespace.rs, crates/kafka/src/topics/mod.rs, crates/kafka/src/topics/routescan.rs, crates/kafka/src/types/mod.rs, crates/kafka/src/types/routescan.rs, crates/routescan/Cargo.toml, crates/routescan/src/lib.rs, crates/routescan/src/types.rs, crates/routescan/tests/it/test.rs, fly/consumer-rtscn/fly.toml
- chore: ini routescan dep
- feat: ini routescan native
=> feat: ini routescan consumer

.github/workflows/fly.yml, crates/axum/src/routes/queue/token.rs, crates/contracts/src/constants.rs
=> feat: ini token protocol

crates/consumer/src/topics/routescan.rs, packages/tables/src/token/token-table.tsx, packages/ui/src/components/table.tsx
- fix: token table last border
- fix: update
=> chore: ini fix rtscan

crates/axum/src/routes/token/update.rs, packages/elements/src/chain-stack.stories.tsx, packages/elements/src/chain-stack.tsx, packages/elements/src/index.ts, packages/tables/src/token/card/token-card-chain.tsx, packages/tables/src/token/token-columns.tsx
- chore: update params
- feat: ini token column id
=> fix: params quote

.changeset/unlucky-llamas-play.md, packages/elements/src/empty-state.tsx, packages/elements/src/invoke-button.tsx, packages/modals/src/address/address-modal.tsx, packages/modals/src/nft/nft-modal.tsx, packages/modals/src/token/token-modal.tsx, packages/msw/src/handlers/token.ts, packages/templates/src/modal/modal.tsx, packages/ui/src/wrappers/layer/base-layer-wrapper.tsx, packages/validators/package.json, pnpm-lock.yaml
- **fix: modal scroll**
- **chore: modal**
=> chore: ini modal mode

.changeset/grumpy-moons-wave.md, packages/hooks/src/index.ts, packages/hooks/src/useIsDemoPathname.ts, packages/tables/src/nft/card/nft-card.tsx, packages/tables/src/token/actions/token-table-row-actions.tsx, packages/tables/src/token/card/token-card-price.tsx, packages/tables/src/token/card/token-card-sparkline.tsx, packages/tables/src/token/token-columns.tsx, packages/ui/src/wrappers/base/base-wrapper.ts
- **feat: ini demo pathname**
- **chore: ini base wrapper refactor**
=> feat: ini demo pathname

apps/inngest/app/api/inngest/route.ts, apps/inngest/src/inngest/prismaSchemaChore.ts, configurations/prisma/migrations/init_wallet_transactions.sql
- **chore: update tx wallet**
- **chore: ini tx hash**
=> chore: ini wallet tx

.changeset/poor-tigers-hunt.md, crates/axum/src/routes/billing_operation/list.rs, crates/axum/src/routes/billing_operation/types.rs, crates/axum/src/routes/paymaster_operation/get.rs, crates/axum/src/routes/paymaster_operation/list.rs, crates/axum/src/routes/paymaster_operation/types.rs
=> feat: ini tx ops

crates/axum/src/routes/billing_operation/list.rs, crates/axum/src/routes/user_operation/get.rs, crates/axum/src/routes/user_operation/list.rs, crates/axum/src/routes/user_operation/types.rs
- **feat: ini typings**
- **chore: update slot**
=> feat: ini billing ops

Makefile, packages/elements/src/token-image.stories.tsx, packages/elements/src/token-image.tsx, packages/tables/src/user-operation/card/user-operation-card-transaction.tsx, packages/templates/src/transaction/transaction.tsx, packages/ui/src/components/pagination.tsx, packages/ui/src/components/skeleton.tsx
=> feat: ini rp tx

apps/app/app/(authenticated)/new/(components)/root/root-context.tsx, packages/modals/src/deposit/deposit-modal.tsx, packages/modals/src/token/token-modal.tsx
- **feat: ini onboarding banner**
=> fix: onboarding light root

.changeset/fifty-otters-tan.md, .contracts-size, apps/app/app/(wallet)/@create/(.)[address]/create/page.tsx, apps/app/app/(wallet)/[address]/activity/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/create/page.tsx, apps/app/app/(wallet)/[address]/deposit/(components)/deposit-dialog.tsx, apps/app/app/(wallet)/[address]/dev/(components)/dev-form.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/history-data-table.tsx, apps/app/app/(wallet)/[address]/overview/nfts/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/overview/nfts/(components)/nfts-data-table.tsx, apps/app/app/(wallet)/[address]/overview/tokens/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/overview/tokens/(components)/tokens-data-table.tsx, apps/app/app/(wallet)/[address]/owners/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, apps/app/app/(wallet)/[address]/settings/deployment/(components)/settings-deployment-card.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/overview/overview-section-empty.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/overview/overview-section.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/transactions-data-table.tsx, apps/app/src/components/nft/nft-portfolio.tsx, apps/app/src/components/nft/nfts-list.tsx, apps/app/src/components/token/tokens-list.tsx, apps/app/src/components/transaction/transactions-list.tsx, apps/app/src/hooks/useTabs.tsx, packages/forms/src/abi-form.tsx, packages/query/src/index.ts, packages/query/src/useQueryNftPortfolio.ts, packages/templates/src/transaction/transaction.tsx
- **feat: ini dev form process**
- **fix: tx bil**
=> feat: ini abi form

.changeset/short-laws-reply.md, apps/app/app/(wallet)/@send/(.)[address]/send/(components)/modal-interception-footer.tsx, apps/app/app/(wallet)/[address]/owners/(components)/data-table/data-table.tsx, apps/app/app/(wallet)/[address]/owners/(components)/owner-overview-banner/owner-overview-banner.tsx, apps/app/app/(wallet)/[address]/owners/(components)/owners-data-table.tsx, apps/app/app/(wallet)/[address]/owners/layout.tsx, packages/nuqs/src/index.ts, packages/nuqs/src/useIsOwnerEditQueryState.ts, packages/nuqs/src/useOwnersQueryState.ts, packages/tables/package.json, packages/tables/src/owner/actions/owner-table-row-actions.tsx, packages/tables/src/owner/owner-columns.tsx, packages/tables/src/owner/owner-table.tsx, pnpm-lock.yaml
- **feat: ini owner table**
- **feat: ini owner edit**
- **feat: ini edit banner**
=> feat: ini edit buton

.changeset/fast-balloons-hope.md, .changeset/hip-weeks-bathe.md, crates/axum/src/routes/configuration_operation/create.rs, packages/client/src/types/api/v1.d.ts, packages/data/src/configurationOperation.ts, packages/data/src/index.ts, packages/forms/package.json, packages/forms/src/owner-form.tsx, packages/hooks/src/useConfigurationOperationCreate.ts, packages/params/src/configurationOperation.ts, packages/params/src/index.ts, packages/query/src/index.ts, packages/query/src/useQueryConfigurationOperationSimulation.ts, packages/query/src/useQueryWalletBilling.ts, packages/query/src/useQueryWalletSimulation.ts, packages/templates/src/progress-transaction/progress-transaction.tsx, packages/templates/src/transaction/transaction.tsx, pnpm-lock.yaml
- **feat: ini configuration op**
- **feat: ini config op**
- **feat: ini configuration simulation**
- **feat: ini wallet billing**
=> feat: ini config op

crates/axum/src/routes/user_operation/signature.rs
=> feat: ini sig

.changeset/thin-donkeys-chew.md, apps/app/app/(wallet)/[address]/create/page.tsx, apps/app/app/(wallet)/[address]/settings/deployment/(components)/settings-deployment-card.tsx, apps/app/src/handlers/[address]/create/handler.ts, configurations/prisma/migrations/delete_configuration.sql, packages/const/src/contract_addresses.ts, packages/const/src/index.ts, packages/hooks/src/useConfigurationOperationCreate.ts, packages/query/package.json, packages/query/src/useMutationUserOperationSend.ts, packages/templates/src/transaction/transaction.tsx, packages/utils/src/contract.ts, pnpm-lock.yaml
- **feat: ini config mappings**
- **chore: update params**
- **feat: ini wallet contract addresses**
=> fix: tx send

.changeset/funny-spiders-peel.md, apps/app/app/(wallet)/[address]/settings/deployment/layout.tsx, apps/subgraph/src/config.ts, configurations/prisma/migrations/update_wallet_v020.sql, crates/contracts/src/constants.rs, crates/sequence/src/hash.rs
=> feat: ini v0.2.0 mig

packages/templates/src/transaction/transaction-fetcher.tsx, packages/templates/src/transaction/transaction.tsx
- **fix: transaction indexing**
- **fix: debounced fetcher**
=> fix: ini debounced fetch

.changeset/clever-otters-repair.md, crates/axum/src/routes/user_operation/create.rs, packages/hooks/src/useUserOperationCreate.ts
=> fix: merkle hash

.changeset/purple-buckets-matter.md, SECURITY.md, apps/app/app/(wallet)/[address]/settings/deployment/(components)/settings-deployment-card.tsx, apps/app/package.json, packages/const/src/contract_addresses.ts, packages/const/src/index.ts, packages/templates/package.json, packages/ui/package.json, packages/wagmi/src/index.ts, pnpm-lock.yaml
=> feat: ini impl versions

.changeset/orange-experts-cheer.md, apps/app/app/(wallet)/[address]/create/layout.tsx, apps/app/app/(wallet)/[address]/deposit/(components)/deposit-dialog.tsx, apps/app/app/(wallet)/[address]/deposit/layout.tsx, apps/app/app/(wallet)/[address]/dev/(components)/dev-form.tsx, apps/app/app/(wallet)/[address]/send/layout.tsx, apps/app/src/components/root/root.tsx, apps/explorer/src/components/root/root.tsx, packages/templates/src/modal/modal.tsx, packages/ui/src/components/badge.tsx, packages/ui/src/components/button-group.tsx, packages/ui/src/components/navigation-menu.tsx, packages/ui/src/components/number.tsx, packages/ui/src/components/timeline.tsx, packages/ui/src/index.ts, packages/ui/src/sections/state-info-section.tsx, packages/ui/src/wrappers/section/dialog-section-wrapper.tsx, packages/ui/src/wrappers/section/index.ts
- **feat: ini modal flex flex-col**
- **chore: ini available one**
- **feat: ini deposit dialog**
- **feat: ini deposit max**
=> fix: overflow container

.changeset/plenty-pugs-mate.md, apps/app/app/(wallet)/@deposit/(.)[address]/deposit/(components)/modal-interception-footer.tsx, apps/app/app/(wallet)/[address]/deposit/(components)/deposit-dialog.tsx, packages/stores/src/useFormRef.ts
- **feat: ini deposit detials**
=> feat: refactor deposit modal

apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, packages/modals/src/address/address-modal.tsx, packages/stores/src/useModals.ts
- **feat: ini addr modal**
- **feat: ini tx queue**
- **feat: ini modal address**
=> fix: address modal

.changeset/brave-items-refuse.md, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, packages/modals/src/address/address-modal.tsx
=> fix: addr modal deb

.changeset/quick-ligers-do.md, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, contracts/test/spec/misc/MerkleProof.spec.ts, crates/axum/src/routes/user_operation/create.rs, packages/hooks/src/useUserOperationCreate.ts
- **feat: ini tx queue**
- **fix: encoding dialog**
=> fix: ini merkle

.changeset/gentle-sheep-dream.md, apps/app/app/(wallet)/[address]/create/(components)/create-dialog.tsx, apps/app/app/(wallet)/[address]/create/page.tsx, contracts/test/spec/misc/MerkleProof.spec.ts, packages/hooks/package.json, packages/hooks/src/useUserOperationCreate.ts, packages/templates/package.json, packages/templates/src/transaction/transaction-fetcher.tsx, packages/templates/src/transaction/transaction.stories.tsx, packages/templates/src/transaction/transaction.tsx, pnpm-lock.yaml
=> feat: ini progress uops

apps/app/app/(wallet)/[address]/deposit/(components)/deposit-dialog.tsx, apps/app/src/components/wss/wss-state.tsx, packages/hooks/src/useConfigurationOperationCreate.ts, packages/hooks/src/useUserOperationCreate.ts, packages/hooks/src/useUserOperationSend.ts, packages/templates/src/transaction/transaction-fetcher.tsx, packages/templates/src/transaction/transaction-sender.tsx, packages/templates/src/transaction/transaction.tsx
- **fix: sender ops**
- **chore: ini pkg log**
=> fix: ini progress ind

.github/workflows/rust.yml, package.json
=> chore: update v2

apps/app/src/hooks/useTabs.tsx, packages/stores/src/useBanners.ts, packages/templates/src/banner/banner.tsx
=> feat: ini owner addr

.changeset/thick-spiders-guess.md, apps/app/app/(wallet)/[address]/deposit/(components)/deposit-dialog.tsx, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, apps/app/app/(wallet)/layout.tsx, apps/app/next.config.mjs, packages/client/src/simplehash/owners.ts, packages/elements/src/nft-image.tsx, packages/tables/src/nft/card/nft-card.tsx
=> feat: ini ppr val

.changeset/little-tomatoes-count.md, .github/workflows/auto-approve.yml, .github/workflows/changesets.yml, .github/workflows/cla.yml, .github/workflows/e2e.yml, .github/workflows/extension.yml, .github/workflows/fastlane.yml, .github/workflows/ios.yml, .github/workflows/node.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/rust.yml, .lintstagedrc.js, apps/app/package.json, apps/inngest/package.json, crates/consumer/src/topics/covalent.rs, package.json, turbo.json
=> feat: ini turbo 

.changeset/dull-bananas-switch.md, apps/app/app/(authenticated)/notifications/page.tsx, apps/app/app/(authenticated)/wallets/page.tsx, apps/app/app/(wallet)/[address]/activity/page.tsx, apps/app/app/(wallet)/[address]/deposit/page.tsx, apps/app/app/(wallet)/[address]/overview/history/page.tsx, apps/app/app/(wallet)/[address]/overview/nfts/page.tsx, apps/app/app/(wallet)/[address]/overview/page.tsx, apps/app/app/(wallet)/[address]/overview/tokens/page.tsx, apps/app/app/(wallet)/[address]/owners/page.tsx, apps/app/app/(wallet)/[address]/send/page.tsx, apps/app/app/(wallet)/[address]/transactions/history/page.tsx, apps/app/app/(wallet)/[address]/transactions/page.tsx, apps/app/app/(wallet)/[address]/transactions/queue/page.tsx, apps/explorer/app/(transaction)/transactions/page.tsx, apps/explorer/app/(transaction)/tx/address/[address]/page.tsx, apps/explorer/app/(user-operation)/address/[address]/page.tsx, apps/explorer/app/(user-operation)/page.tsx, packages/templates/src/notification-combo-dialog/notification-combo-dialog.tsx, packages/ui/.depcheckrc.yml, packages/ui/src/providers/react-query.tsx
=> fix: cache handler

.changeset/giant-mugs-shop.md, apps/app/app/(wallet)/[address]/dev/(components)/dev-form.tsx, apps/app/app/(wallet)/[address]/settings/deployment/(components)/settings-deployment-card.tsx, apps/app/src/components/settings/settings-card.tsx, packages/hooks/src/useUserOperationCreate.ts, packages/stores/src/useUserOperations.ts, packages/templates/src/transaction/transaction-fetcher.tsx, packages/templates/src/transaction/transaction.tsx
- **feat: ini deployment card**
=> feat: ini address comp

.changeset/many-pans-swim.md, apps/app/app/(wallet)/@create/(.)[address]/create/page.tsx, packages/templates/src/index.ts, packages/templates/src/modal-interception/modal-interception.tsx, packages/templates/src/modal-swiper/modal-swiper.tsx, packages/templates/src/modal/index.ts, packages/templates/src/modal/modal.tsx, packages/templates/src/transaction/transaction-fetcher.tsx, packages/templates/src/transaction/transaction.tsx, packages/ui/src/components/tabs.tsx
=> feat: ini sticky tab

apps/app/middleware.ts, apps/router/.depcheckrc.yml, apps/router/.gitignore, apps/router/package.json, apps/router/src/index.ts, apps/router/src/proxy.ts, packages/const/src/api_urls.ts, packages/const/src/index.ts
=> feat: ini lifi router

.changeset/tender-doors-visit.md, apps/app/src/components/cart/cart-badge-count-button.tsx, apps/app/src/components/nav/app-nav.tsx, apps/app/src/components/root/root.tsx, packages/modals/src/address/address-modal.tsx, packages/modals/src/auth/auth-modal.tsx, packages/modals/src/cart/cart-modal.stories.tsx, packages/modals/src/cart/cart-modal.tsx, packages/modals/src/chain/chain-modal.tsx, packages/modals/src/connect/connect-modal.tsx, packages/modals/src/nft/nft-modal.tsx, packages/modals/src/owner/owner-modal.tsx, packages/modals/src/token/token-modal.tsx, packages/stores/src/useModals.ts, packages/templates/src/badge-count-button/badge-count-button.stories.tsx, packages/templates/src/badge-count-button/badge-count-button.tsx, packages/templates/src/badge-count-button/index.ts, packages/templates/src/index.ts, packages/templates/src/modal-interception/modal-interception.tsx, packages/templates/src/modal/modal.tsx, packages/templates/src/notification-combo-dialog/notification-combo-dialog.tsx, packages/ui/src/components/drawer.tsx, packages/ui/src/components/sheet.tsx, packages/ui/src/index.ts
- **feat: ini badge count buton**
- **feat: ini badge count**
=> feat: ini badge cart

apps/app/app/(authenticated)/support/layout.tsx, apps/app/app/(authenticated)/support/page.tsx, crates/graphql/src/wallets/mod.rs, packages/templates/src/cal/cal.tsx
=> chore: ini support page

.changeset/shaggy-poems-admire.md, packages/modals/package.json, packages/modals/src/chain/chain-modal.tsx, packages/modals/src/token/token-modal.stories.tsx, packages/modals/src/token/token-modal.tsx, packages/nuqs/src/index.ts, packages/nuqs/src/useChainQueryState.ts, pnpm-lock.yaml
- **feat: ini token modal set**
- **chore: update send**
=> feat: ini chain modal

apps/app/app/(demo)/demo/send/new/page.tsx, apps/app/app/(demo)/demo/swap/layout.tsx, apps/app/app/(demo)/demo/swap/new/page.tsx, apps/app/app/(demo)/demo/swap/page.tsx, apps/app/app/(wallet)/[address]/(const)/nav-items.ts, apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner/wallet-overview-banner-address.tsx, apps/app/app/(wallet)/[address]/swap/page.tsx, apps/app/app/@swap/(.)demo/send/page.tsx, apps/app/app/@swap/default.tsx, apps/app/app/layout.tsx, apps/app/package.json, apps/app/src/components/section/link-button-group.tsx, apps/app/src/const/tabs.tsx, apps/app/src/const/titles.ts
- **feat: ini nav button**
- **feat: ini swap demo**
=> feat: ini swap

crates/constants/src/chains.rs, crates/rpc/src/constants.rs, packages/const/src/chains.ts, packages/svg/src/chain/index.tsx, packages/svg/src/chain/sei.tsx, thunder-tests/thunderActivity.json
- **feat: ini sei**
- **chore: ini sei logoo**
- **feat: ini chain rc**
=> chore: ini const

.changeset/hot-doors-tie.md, crates/paymaster/src/paymaster.rs, thunder-tests/thunderActivity.json
=> fix: pop op

crates/contracts/src/types.rs, crates/paymaster/src/config.rs, crates/paymaster/src/constants.rs, crates/paymaster/src/paymaster.rs, crates/rpc/src/constants.rs, thunder-tests/collections/tc_col_local.json, thunder-tests/collections/tc_col_rpclightso.json
- **feat: ini alchemy policies**
- **chore: update config pm**
=> feat: ini alchemy pm

.changeset/forty-flies-pay.md, packages/elements/src/nft-image.tsx, packages/modals/src/cart/cart-modal.tsx, packages/query/src/useQueryPaymasterGasAndPaymasterAndData.ts, packages/templates/src/transaction/transaction-fetcher.tsx, thunder-tests/collections/tc_col_local.json, thunder-tests/collections/tc_col_rpclightso.json
=> fix: ini cart modal

apps/app/app/(wallet)/[address]/create/layout.tsx, configurations/prisma/prisma/schema-rs.prisma, configurations/prisma/prisma/schema.prisma
=> chore: update pop ts

.changeset/eighty-years-learn.md, crates/consumer/src/topics/paymaster_operation.rs, crates/contracts/src/types.rs, crates/kafka/src/types/paymaster_operation.rs, crates/paymaster/src/paymaster.rs, packages/templates/src/modal-interception/modal-interception.tsx, packages/templates/src/modal/modal.tsx
=> feat: ini modal sizing

packages/hooks/src/useUserOperationFeePerGas.ts, packages/query/src/useQueryPaymasterGasAndPaymasterAndData.ts, packages/stores/src/useGasSpeed.ts, packages/templates/src/transaction/transaction-fetcher.tsx, project-words.txt
- **feat: ini useroperation fee gas**
=> fix: ini gas query

apps/app/next.config.mjs, apps/blog/app/(blog)/page.tsx, apps/blog/app/(post)/[...slug]/page.tsx, apps/blog/app/api/keystatic/posts/route.ts, apps/blog/keystatic.config.ts, apps/changelog/app/(changelog)/page.tsx, apps/changelog/app/(post)/[...slug]/page.tsx, apps/changelog/app/api/keystatic/posts/route.ts, apps/changelog/content/2024/07/my-first-post.md, apps/changelog/keystatic.config.ts, apps/changelog/src/const/titles.ts, apps/proposals/app/(post)/[...slug]/page.tsx, apps/proposals/app/(proposals)/page.tsx, apps/proposals/app/api/keystatic/posts/route.ts, apps/proposals/keystatic.config.ts
- **fix: proposals root**
- **feat: update**
=> feat: ini proposals

apps/app/next.config.mjs, apps/blog/next.config.mjs, apps/changelog/next.config.mjs, apps/proposals/next.config.mjs, configurations/styles/keystatic.css, packages/const/src/internal_links.ts, packages/hooks/src/useUserOperationSend.ts, packages/query/src/useMutationQueueUserOperation.ts
- **fix: send compound**
- **feat: update props**
=> fix: ini proposals v4

apps/app/next.config.mjs, apps/blog/next.config.mjs, apps/changelog/next.config.mjs, apps/proposals/next.config.mjs
=> fix: ini man

apps/blog/app/(blog)/page.tsx, apps/changelog/app/(changelog)/page.tsx, apps/proposals/app/(proposals)/page.tsx, apps/proposals/content/proposals/lip-1.md, packages/const/src/internal_links.ts
- **fix: changes log**
- **fix: asset proposals**
=> fix: ini root loading

.changeset/quiet-adults-drive.md, apps/app/src/components/root/root.tsx, packages/hooks/src/useUserOperationSend.ts, packages/hooks/src/useUserOperationsCreate.ts, packages/hooks/src/useUserOperationsCreateState.ts, packages/hooks/src/useUserOperationsSendState.ts, packages/query/src/useMutationUserOperationCreate.ts, packages/query/src/useMutationUserOperationCreateBatch.ts, packages/states/src/form-state.tsx, packages/states/src/index.ts, packages/states/src/user-operation-state.tsx, packages/stores/src/useUserOperations.ts, packages/templates/src/transaction/transaction-sender.tsx, packages/templates/src/transaction/transaction.tsx
- **feat: ini form state**
- **feat: ini uop state**
=> feat: ini auth

apps/app/src/components/command-k.tsx, packages/states/src/user-operation-state.tsx, packages/stores/src/useSettings.ts, packages/templates/src/progress-user-operation/progress-user-operation.tsx, packages/templates/src/transaction/transaction-sender.tsx, packages/ui/package.json, packages/ui/src/providers/react-query.tsx, pnpm-lock.yaml
=> feat: ini query states

packages/templates/src/root/root.tsx, packages/templates/src/transaction/transaction-sender.tsx, packages/ui/src/providers/react-query.tsx
=> fix: ini send tx desc

packages/hooks/src/useUserOperationSend.ts, packages/query/src/index.ts, packages/query/src/useMutationStateUserOperationReceipt.ts, packages/query/src/useMutationUserOperationSend.ts, packages/query/src/useQueryUserOperationReceipt.ts, packages/states/src/user-operation-state.tsx, packages/tables/src/user-operation/card/user-operation-card-transaction-execute-button.tsx, packages/templates/src/progress-user-operation/progress-user-operation.tsx
- **fix: ini button exec**
- **fix: op send**
- **fix: ini sucking**
=> chore: ini ops send

Cargo.lock, crates/axum/src/routes/user_operation/create.rs, crates/contracts/Cargo.toml, crates/contracts/src/types.rs, crates/node/Cargo.toml, crates/node/src/node.rs
- **chore: ini backon node**
- **chore: ini types node**
- **chore: ini reate**
=> feat: ini node backon

crates/axum/src/routes/queue/node.rs, crates/axum/src/routes/user_operation/create.rs, packages/templates/src/transaction/transaction-status.tsx
=> fix: ini status page

apps/explorer/.env.development, apps/explorer/app/(user-operation)/op/[userOperationHash]/(components)/op-data-table.tsx, apps/explorer/app/(user-operation)/op/[userOperationHash]/page.tsx, apps/explorer/app/(user-operation)/ops/[userOperationMerkleRoot]/(components)/op-data-table.tsx, apps/explorer/app/(user-operation)/ops/[userOperationMerkleRoot]/page.tsx, apps/explorer/app/(user-operation)/page.tsx, apps/explorer/package.json, apps/explorer/src/handlers/op/[userOperationHash]/handler.ts, apps/explorer/src/handlers/ops/[userOperationMerkleRoot]/handler.ts, apps/explorer/src/preloaders/op/[userOperationHash]/preloader.ts, apps/explorer/src/preloaders/ops/[userOperationMerkleRoot]/preloader.ts, apps/frames/package.json, packages/services/src/getUserOperationMerkle.ts, packages/services/src/index.ts, packages/validators/src/userOperationMerkleRoot.ts
- **feat: ini op hash**
- **feat: ini merkle root**
=> feat: ini explorer ops

.changeset/long-parrots-smash.md, apps/app/src/components/root/root.tsx, apps/app/src/components/state/wallet-state.tsx, apps/app/src/components/web3/wallet-switcher.tsx, crates/axum/src/routes/token/get.rs, packages/client/src/api/token.ts, packages/client/src/types/api/v1.d.ts, packages/dialogs/src/swap/swap.tsx, packages/params/src/token.ts, packages/query/src/useQueryToken.ts, packages/schemas/src/eth/swap.ts, packages/states/package.json, packages/states/src/auth-state.tsx, packages/ui/src/components/button-icon.tsx, packages/ui/src/components/button.tsx, packages/wagmi/src/index.ts, pnpm-lock.yaml
- **feat: ini wallet switcher**
=> feat: ini switcher wal

.changeset/purple-apples-applaud.md, .license-check-and-add-config.json, apps/router/package.json, apps/router/src/index.ts, cspell.json, packages/client/src/client.ts, packages/client/src/lifi/index.ts, packages/client/src/lifi/quote.ts, packages/data/package.json, packages/data/src/index.ts, packages/data/src/lifi.ts, packages/dialogs/src/swap/swap.tsx, packages/params/src/index.ts, packages/params/src/lifi.ts, packages/query-keys/src/index.ts, packages/query-keys/src/lifi.ts, packages/query/src/index.ts, packages/query/src/useQueryLifiQuote.ts, packages/ui/src/components/textarea.tsx, pnpm-lock.yaml
- **chore: ini symbol tokens**
- **chore: ini swap**
- **chore: update swap demo**
- **chore: update buy swap**
- **chore: update lifi swap**
- **chore: ini swap empty**
=> feat: ini swap restlying

.changeset/strange-rats-wash.md, apps/app/app/(wallet)/[address]/op/[userOperationHash]/(components)/op-data-table.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/data-table/data-table.tsx, apps/explorer/app/(user-operation)/(components)/data-table/data-table.tsx, apps/explorer/app/(user-operation)/op/[userOperationHash]/(components)/op-data-table.tsx, packages/tables/src/index.ts, packages/tables/src/user-operation/actions/user-operation-table-row-actions.tsx, packages/tables/src/user-operation/card/user-operation-card-transaction.tsx, packages/tables/src/user-operation/index.ts, packages/tables/src/user-operation/user-operation-table.tsx
- **feat: ini uop table type**
=> feat: ini hooks tabular

.changeset/twenty-weeks-hunt.md, Cargo.lock, crates/consumer/src/topics/node.rs, crates/contracts/Cargo.toml, crates/contracts/src/lib.rs, crates/contracts/src/tracer.rs, crates/contracts/src/user_operation.rs, crates/node/src/node.rs
- **feat: ini node op**
- **chore: udpate op cope**
=> feat: ini uop node

crates/interpreter/src/config.rs, package.json, packages/dialogs/src/transaction/transaction-fetcher.tsx, packages/wagmi/src/generated.ts, packages/wagmi/src/index.ts, wagmi.config.ts
- **feat: ini tx fetcher**
- **fix: ini config**
=> feat: ini uop nonce

.changeset/beige-feet-lay.md, packages/dialogs/src/transaction/transaction-fetcher.tsx
- **fix: entrypoint nonce**
- **fix: tx fetcher**
=> fix: tx fetcher

.changeset/poor-bikes-shake.md, apps/app/app/(wallet)/[address]/send/(components)/send-dialog.tsx, packages/client/src/lifi/index.ts, packages/client/src/lifi/tokens.ts, packages/data/src/index.ts, packages/data/src/lifi.ts, packages/dialogs/src/swap/swap.tsx, packages/dialogs/src/transaction/transaction-fetcher.tsx, packages/dialogs/src/transaction/transaction.tsx, packages/elements/src/token-image.tsx, packages/hooks/package.json, packages/hooks/src/useSwap.ts, packages/hooks/src/useUserOperationsCreate.ts, packages/modals/package.json, packages/modals/src/token/token-modal.stories.tsx, packages/modals/src/token/token-modal.tsx, packages/query-keys/src/lifi.ts, packages/query/src/index.ts, packages/query/src/useQueryLifiTokens.ts, packages/stores/src/useModals.ts, pnpm-lock.yaml
- **feat: ini multi feat tokens**
=> feat: ini filter tokens

.changeset/swift-trees-smile.md, package.json, packages/dialogs/package.json, packages/dialogs/src/swap/swap.tsx, packages/elements/src/token-image.tsx, packages/hooks/src/index.ts, packages/hooks/src/useSwap.ts, packages/hooks/src/useWagmiToken.ts, packages/modals/src/token/token-modal.tsx, packages/query/src/useQueryLifiTokens.ts, pnpm-lock.yaml
- **feat: ini token modal swap**
- **chore: ini modal swap**
- **feat: ini wagmi token**
- **feat: ini swap details**
- **chore: ini token image**
=> feat: ini query modal lif

crates/axum/src/routes/token/list.rs, crates/axum/src/routes/token/types.rs, crates/axum/src/routes/token_group/get.rs, crates/axum/src/routes/token_group/list.rs, crates/axum/src/routes/token_group/types.rs, crates/consumer/src/topics/node.rs, crates/node/src/node.rs, packages/client/src/types/api/v1.d.ts
- **feat: ini backon node**
- **feat: ini token group list**
- **feat: ini is testnet**
- **chore: update v1 data**
=> feat: ini group api

packages/dialogs/src/swap/swap.tsx, packages/hooks/src/useToken.ts, packages/hooks/src/useTokenAmount.ts, packages/modals/src/token/token-modal.tsx, packages/types/src/token.ts
- **chore: udpate token modal**
- **chore: ini token amount**
=> feat: ini group tokens routing

apps/paper/pages/use-cases/list.mdx, apps/paper/pages/use-cases/transaction-graph.mdx, packages/dialogs/src/swap/swap.tsx
- **fix: swap hooks**
- **feat: ini tx graph**
=> fix: ini swap overview

.changeset/perfect-gifts-promise.md, packages/dialogs/src/swap/swap.tsx, packages/hooks/src/index.ts, packages/hooks/src/useQuote.ts, packages/hooks/src/useSwap.ts, packages/nuqs/src/useSwapQueryState.ts, packages/query/src/useQueryLifiQuote.ts, packages/stores/src/index.ts, packages/stores/src/useQuotes.ts, packages/stores/src/useTokenGroups.ts, packages/stores/src/useTransactions.ts, packages/stores/src/useUserOperations.ts
=> feat: ini quotes

.changeset/soft-glasses-whisper.md, packages/dialogs/src/swap/swap.tsx, packages/dialogs/src/transaction/transaction.tsx
=> fix: ini query state params

.changeset/soft-glasses-whisper.md, apps/app/src/components/state/wallet-state.tsx, packages/dialogs/src/swap/swap.tsx, packages/dialogs/src/transaction/transaction.tsx, packages/stores/src/useAuth.ts
- **chore: ini swap finder**
- **chore: update swap token**
- **fix: tx params**
- **fix: logs**
=> fix: dialog params

.changeset/breezy-files-boil.md, packages/dialogs/src/swap/swap.tsx, packages/states/src/user-operation-state.tsx
- **fix: hydrate**
- **fix: count**
=> fix: auto swaps

.husky/commit-msg, .husky/pre-commit, .husky/prepare-commit-msg, apps/app/src/handlers/[address]/create/handler.ts, apps/app/src/handlers/create/handler.ts, package.json, packages/dialogs/src/swap/swap.tsx, packages/hooks/src/useQuote.ts, packages/hooks/src/useUserOperationsProgress.ts
=> feat: ini uop fix

crates/consumer/src/topics/node.rs, crates/node/src/node.rs, packages/dialogs/src/transaction/transaction.tsx
=> fix: node backon

.changeset/mean-lamps-fail.md, packages/dialogs/src/swap/swap.tsx, packages/dialogs/src/transaction/transaction-fetcher.tsx, packages/hooks/src/useDebouncedValue.ts, packages/hooks/src/useSwap.ts, packages/modals/src/address/address-modal.tsx, packages/modals/src/token/token-modal.tsx, packages/query/src/useQueryUserOperationEstimateFeesPerGas.ts, packages/query/src/useQueryUserOperationEstimateGas.ts
=> fix: est fee gas

.changeset/ninety-goats-kneel.md, packages/templates/src/modal-interception/modal-interception.tsx
=> fix: modal reset

crates/db/src/models/user_operation.rs, crates/polling/src/polling.rs
=> fix: ini upsert logs

.changeset/rude-spoons-poke.md, crates/rpc/src/constants.rs, crates/rpc/src/lib.rs
=> fix: ini rpc urls

.husky/pre-commit, packages/dialogs/src/transaction/transaction-fetcher.tsx, packages/query/src/useQueryPaymasterGasAndPaymasterAndData.ts
- **fix: tx fetcher**
- **test: asdf**
=> fix: ini fetcher

.changeset/sweet-dogs-lie.md, Cargo.lock, crates/billing/src/billing.rs, crates/constants/src/chains.rs, crates/graphql/src/constants.rs, crates/polling/Cargo.toml, crates/polling/src/config.rs, crates/polling/src/polling.rs, crates/utils/src/lib.rs
- **feat: update uop duration**
=> feat: ini bop

packages/elements/src/next-image.tsx
=> fix: cloudflare

apps/changelog/app/(changelog)/page.tsx, apps/changelog/next.config.mjs, packages/elements/src/next-image.tsx
=> fix: ini next image cf

.changeset/late-pianos-perform.md, apps/blog/app/(blog)/page.tsx, apps/blog/content/integrations/my-first-post.md, apps/blog/content/integrations/my-fourth-post.md, apps/blog/content/integrations/my-second-post.md, apps/blog/content/integrations/my-third-post.md, apps/blog/keystatic.config.ts, apps/blog/package.json, apps/changelog/app/(changelog)/page.tsx, apps/changelog/package.json, apps/explorer/src/const/tabs.tsx, apps/images/package.json, biome.json, packages/elements/src/next-image.tsx, packages/templates/src/nav/nav-location.tsx, packages/utils/src/date.ts, packages/utils/src/index.ts, pnpm-lock.yaml
- **feat: ini next image page**
- **feat: ini cf loader**
=> feat: ini blog integration

apps/home/app/(components)/chains.tsx, apps/home/app/(components)/cta.tsx, apps/home/app/(components)/features.tsx, apps/home/app/(components)/unified.tsx, apps/home/app/page.tsx, apps/home/package.json, apps/home/src/components/grid.tsx, apps/home/src/components/menu.tsx, pnpm-lock.yaml, project-words.txt
- **feat: ini feature card**
- **feat: ini chains features**
- **feat: update chians**
=> feat: ini home features

.changeset/mighty-tigers-raise.md, apps/ai/src/ai/actions/submitUserMessage.tsx, apps/ai/src/ai/handlers/botMessage.tsx, apps/ai/src/ai/server.tsx, apps/ai/src/components/chat-share-dialog.tsx
=> feat: ini ai handlers

packages/elements/src/token-image.tsx
Fixes: https://github.com/LightDotSo/LightDotSo/issues/2238
=> chore: Update token-image.tsx

.changeset/rude-otters-obey.md, Cargo.lock, Cargo.toml, crates/axum/src/api.rs, crates/axum/src/error.rs, crates/axum/src/routes/billing_operation/get.rs, crates/axum/src/routes/configuration_operation/create.rs, crates/axum/src/routes/configuration_operation/types.rs, crates/axum/src/routes/interpretation_action/get.rs, crates/axum/src/routes/mod.rs, crates/axum/src/routes/notification_settings/get.rs, crates/axum/src/routes/operation/error.rs, crates/axum/src/routes/operation/list.rs, crates/axum/src/routes/operation/mod.rs, crates/axum/src/routes/operation/types.rs, crates/axum/src/routes/transaction/list.rs, crates/axum/src/routes/user_operation/list.rs, crates/axum/src/routes/user_operation/types.rs, crates/dag/Cargo.toml, crates/dag/src/lib.rs, crates/dag/src/main.rs, crates/db/src/models/interpretation.rs, project-words.txt
- **feat: ini dagre js**
- **feat: ini operation list**
=> feat: ini dag run

apps/blog/app/(blog)/page.tsx, apps/blog/app/(post)/[...slug]/page.tsx, apps/blog/content/announcements/lightpaper.mdx, apps/blog/content/integrations/sample-integration.mdx, packages/ui/src/wrappers/layer/base-layer-wrapper.tsx
=> fix: ini blog layout

.changeset/spotty-deers-arrive.md, packages/ui/clean-package.config.json
=> fix: ini ui index

packages/ui/scripts/tsup.build.ts
=> fix: ini export tsup

apps/app/app/(wallet)/[address]/overview/(components)/overview/overview-list.tsx, apps/app/app/(wallet)/[address]/overview/(components)/wallet-overview-banner/wallet-overview-banner.tsx, packages/widget/.depcheckrc.yml, packages/widget/package.json, packages/widget/postcss.config.js, packages/widget/src/index.tsx, packages/widget/tailwind.config.js, packages/widget/tsconfig.json, packages/widget/tsup.config.ts, packages/widget/turbo.json, pnpm-lock.yaml
=> feat: ini w rename

apps/ai/package.json, apps/app/app/(wallet)/[address]/settings/page.tsx, apps/app/src/components/web3/wallet-switcher.tsx, apps/blog/.depcheckrc.yml, apps/changelog/.depcheckrc.yml, apps/docs/app/layout.tsx, apps/docs/content-collections.ts, apps/docs/package.json, apps/home/.depcheckrc.yml, packages/roots/src/light/light-root-wrapper.tsx, packages/ui/src/providers/web3/web3.tsx, pnpm-lock.yaml
- **chore: ini apps logs**
- **feat: ini apps docs fix**
=> feat: docs config

apps/app/app/(wallet)/[address]/settings/loader.tsx, apps/app/app/(wallet)/[address]/settings/page.tsx, apps/home/.depcheckrc.yml, apps/home/app/(components)/swap-dialog-loader.tsx, apps/home/app/(sections)/swap.tsx, apps/home/package.json, apps/home/src/components/menu.tsx, apps/home/tsconfig.json, packages/templates/src/data-table/data-table-column-header.tsx, pnpm-lock.yaml
- **feat: ini home app**
- **feat: ini app menu**
- **chore: ini menu home**
=> feat: ini home app

apps/app/app/(wallet)/[address]/transactions/(components)/overview/overview-list.tsx, apps/app/app/(wallet)/[address]/transactions/loading.tsx, apps/app/app/(wallet)/[address]/transactions/page.tsx, apps/blog/app/layout.tsx, apps/home/app/layout.tsx
- **fix: light blog**
- **feat: ini list update**
=> fix: ini overview list

apps/app/app/(action)/(components)/floating-icon.tsx, apps/app/app/(action)/(components)/floating.tsx, apps/app/app/(action)/(layouts)/base-layout.tsx, apps/app/app/(action)/(layouts)/intro-layout.tsx, apps/app/app/(action)/deposit/page.tsx, apps/app/app/(action)/layout.tsx, apps/app/app/(action)/send/loading.tsx, apps/app/app/(action)/send/page.tsx, apps/app/app/(action)/swap/(components)/floating-icon.tsx, apps/app/app/(action)/swap/loading.tsx, apps/app/app/(action)/swap/page.tsx, apps/app/app/(unauthenticated)/(components)/root-welcome-cards.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/history-data-table.tsx, apps/app/next.config.mjs, apps/app/package.json, apps/home/package.json, packages/svg/src/chain/index.tsx, packages/utils/src/index.ts, packages/utils/src/shuffle.ts, pnpm-lock.yaml
- **feat: ini floating logos**
- **feat: ini floating logo**
=> feat: ini floating logos

apps/app/src/components/section/link-button-group.tsx
=> fix: batch fix pt.1

apps/blog/content/partnerships/jiffyscan.mdx, apps/blog/content/partnerships/sample-integration.md, apps/home/app/(sections)/swap.tsx, apps/storybook/.storybook/preview.tsx, apps/storybook/package.json, packages/dialogs/src/swap/swap.stories.tsx, packages/dialogs/src/swap/swap.tsx, packages/templates/src/nav/nav-location.tsx, packages/templates/src/nav/nav.tsx, pnpm-lock.yaml
- **feat: ini jiffyscan nav**
- **feat: ini blog**
=> fix: ini nav

.changeset/mean-nails-roll.md, apps/storybook/.depcheckrc.yml, packages/svg/src/index.ts
=> fix: ui exports

.changeset/funny-berries-warn.md, apps/app/app/(authenticated)/notifications/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(authenticated)/wallets/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/activity/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/overview/history/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/overview/nfts/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/overview/tokens/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/owners/(components)/data-table/data-table-toolbar.tsx, apps/app/app/(wallet)/[address]/transactions/(components)/data-table/data-table-toolbar.tsx, apps/app/src/components/section/link-button-group.tsx, apps/explorer/app/(transaction)/(components)/data-table/data-table-toolbar.tsx, apps/explorer/app/(user-operation)/(components)/data-table/data-table-toolbar.tsx
=> fix: table columns

.changeset/light-brooms-clean.md, apps/app/next.config.mjs, apps/home/app/page.tsx, apps/home/src/components/section-pill.tsx, assets/.depcheckrc.yml, assets/exclude.txt, packages/ui/src/components/button/button.tsx, project-words.txt
- **fix: ini ui button**
- **chore: updat**
=> fix: ini ui fixes

.changeset/violet-vans-compare.md, apps/docs/.depcheckrc.yml, apps/docs/app/[[...slug]]/page.tsx, apps/docs/app/source.ts, apps/docs/content/(api)/activity/v1_activity_get_handler.mdx, apps/docs/content/(api)/activity/v1_activity_list_count_handler.mdx, apps/docs/content/(api)/activity/v1_activity_list_handler.mdx, apps/docs/package.json, apps/docs/scripts/generate-docs.mjs, apps/docs/source.config.ts, packages/const/src/social_links.ts, pnpm-lock.yaml
=> feat: ini docs

.changeset/smooth-jobs-matter.md, apps/docs/tsconfig.json, configurations/tsconfig/nextjs.json, configurations/tsconfig/node.json, configurations/tsconfig/react.json, packages/popup/tsconfig.json
- **feat: ini tsconfig refactor**
=> feat: ini tsconfig refactor

.cargo/config.toml, crates/contracts/src/paymaster.rs, crates/paymaster/src/paymaster.rs
=> feat: ini cargo

Cargo.lock, Cargo.toml, apps/blog/content/announcements/light-swaps.mdx, apps/changelog/content/2024/09/2024-09-11-tokio-upgrade.mdx, configurations/styles/keystatic.css, crates/rpc/Cargo.toml, crates/rpc/src/lib.rs, thunder-tests/collections/tc_col_local.json
- **fix: lib entry**
- **feat: ini light cargo**
=> fix: ini error lib

assets/.gitignore, packages/elements/clean-package.config.json, packages/elements/src/base-image/base-image.stories.tsx, packages/elements/src/base-image/base-image.tsx, packages/elements/src/base-image/index.ts, packages/elements/src/external-link/external-link.tsx, packages/elements/src/nft-image/nft-image.tsx, packages/tables/src/user-operation/card/user-operation-card-transaction.tsx
- **fix: ini base image**
- **fix: external link shrink**
=> fix: ui issues

.changeset/sour-fishes-change.md, packages/tables/src/token/token-table.tsx, packages/tables/src/transaction/transaction-table.tsx
=> fix: ini tables ui

package.json, patches/INSTRUCTIONS.md, patches/fumadocs-ui.patch, pnpm-lock.yaml
=> fix: ini patch fuma

.changeset/light-points-prove.md, apps/ai/package.json, cspell.json, packages/templates/package.json, pnpm-lock.yaml
=> fix: ini ncu upgrade

apps/docs/app/source.ts
- **feat: ini prod docs prefix**
=> feat: ini prod docs prefix

apps/app/app/(action)/error.tsx, apps/app/app/(authenticated)/error.tsx, apps/app/app/(demo)/error.tsx, apps/app/app/(unauthenticated)/error.tsx, apps/app/app/(wallet)/error.tsx, apps/app/app/global-error.tsx, apps/blog/app/global-error.tsx, apps/changelog/app/global-error.tsx, apps/explorer/app/global-error.tsx, apps/proposals/app/global-error.tsx, patches/fumadocs-ui.patch, pnpm-lock.yaml
=> feat: ini docs prefix

apps/docs/app/source.ts, package.json, patches/INSTRUCTIONS.md, patches/fumadocs-core@13.4.10.patch, patches/fumadocs-ui@13.4.10.patch, pnpm-lock.yaml
=> fix: ini docs href

apps/docs/content/meta.json, patches/fumadocs-ui@13.4.10.patch, pnpm-lock.yaml
=> fix: ini patch docs

apps/app/app/(wallet)/[address]/overview/@nav/page.tsx, apps/app/app/(wallet)/[address]/transactions/@nav/page.tsx, apps/blog/app/keystatic/[[...params]]/page.tsx, apps/changelog/app/keystatic/[[...params]]/page.tsx, apps/proposals/app/keystatic/[[...params]]/page.tsx
=> fix: ini client page

packages/dialogs/src/transaction/transaction-fetcher.tsx, packages/hooks/src/useEntryPointVersion.ts, packages/hooks/src/useQuote.ts, packages/hooks/src/useUserOperationSend.ts, packages/hooks/src/useUserOperationsProgress.ts, packages/sdk/src/contracts.ts, packages/sdk/src/index.ts, packages/sdk/src/partial-user-operations.ts, packages/sdk/src/paymaster.ts
- **feat: ini entrypoint version hook**
- **chore: update fac cont**
=> fix: ini query

FEATURED.md, apps/app/app/(wallet)/[address]/settings/deployment/(components)/settings-deployment-card.tsx, packages/hooks/src/useProxyImplementationAddress.ts
- **fix: pop 7**
- **fix: contrats index**
=> fix: ini po7

FEATURED.md, apps/app/next.config.mjs, packages/dialogs/src/transaction/transaction-fetcher.tsx, packages/hooks/src/useUserOperationsCreate.ts
=> fix: ini puop

apps/app/next.config.mjs
- **fix: ini app**
- **fix: ini app**
=> fix: ini app

apps/ai/vercel.json, apps/app/vercel.json, apps/blog/vercel.json, apps/changelog/vercel.json, apps/docs/package.json, apps/docs/turbo.json, apps/docs/vercel.json, apps/explorer/vercel.json, apps/frames/vercel.json, apps/home/vercel.json, apps/inngest/vercel.json, apps/paper/vercel.json, apps/proposals/vercel.json, apps/storybook/vercel.json
=> fix: ini app dir

Cargo.lock, crates/redis/src/lib.rs, crates/signer/Cargo.toml, crates/signer/src/connect.rs, crates/signer/src/kms.rs, crates/signer/tests/it/main.rs
=> fix: ini kms lock

apps/app/next.config.mjs, packages/roots/src/root/root.tsx, packages/ui/package.json, packages/ui/src/providers/posthog/index.ts, packages/ui/src/providers/posthog/posthog-pageview.tsx, packages/ui/src/providers/posthog/posthog.tsx, pnpm-lock.yaml, project-words.txt
- **feat: ini posthog weekend**
=> feat: ini posthog query
